// Generated by scripts/import (npm run import) — do not edit.
import type { EntityId, RichContent } from '@/types/content';

// Utility copy and project delivery terms (Project.deliveryTermsId).
export const utilityContent: { id: EntityId; body: RichContent }[] = [
  {
    id: 'project-terms-1',
    body: {
      format: 'sanitized-html',
      html: '<h4><strong>HÌNH THỨC THANH TOÁN:</strong></h4> » Lần 1: 50% sau khi ký hợp đồng. » Lần 2: 50% khi nhận bàn giao website <h4><strong>THỜI GIAN THỰC HIỆN:</strong></h4> » Lên giao diện Demo trong vòng: 10 – 15 ngày » Tiến hành lập trình: 25 – 30 ngày <strong>Lưu ý:</strong> Thời gian chỉ mang tính chất tham khảo, trong quá trình làm cần có sự thống nhất 2 bên để tiến độ Web sẽ sớm hoàn thành. <h4><strong>THỜI GIAN BẢO HÀNH:</strong></h4> » Bảo hành website vĩnh viễn trong trường hợp khách hàng sử dụng Hosting tại <strong>Sova</strong> » Bảo hành 1 năm đối với khách hàng sử dụng Hosting tại đơn vị khác. » Hỗ trợ khách hàng miễn phí trong quá trình sử dụng website. <h4><strong>BÀN GIAO WESITE:</strong></h4> » Website hoàn chỉnh theo mẫu » Bản thiết kế website » Admin quản trị website » Thông tin hướng dẫn quản trị website',
      assetIds: [],
      sources: [
        { file: 'featured_item/evc-athena-cong-ty-tnhh-evc-athena/index.html', line: 754 },
        { file: 'featured_item/centro-noi-that-cao-cap-centro-chau-au/index.html', line: 755 },
        {
          file: 'featured_item/muagiday-san-thuong-mai-dien-tu-xuyen-bien-gioi-hang-dau-viet-nam/index.html',
          line: 754,
        },
        { file: 'featured_item/pink-nail-spa-beauty/index.html', line: 754 },
        {
          file: 'featured_item/pa-marketing-don-vi-dao-tao-hang-dau-ve-marketing/index.html',
          line: 754,
        },
        {
          file: 'featured_item/nhamoi-architechture-kien-truc-dep-cho-moi-nha/index.html',
          line: 754,
        },
        {
          file: 'featured_item/cong-ty-co-phan-kien-truc-va-xay-dung-gt-house/index.html',
          line: 754,
        },
        { file: 'featured_item/bossman-cong-ty-co-phan-bossman-viet-nam/index.html', line: 754 },
        { file: 'featured_item/iphone-hd-iphone-trong-tam-tay/index.html', line: 754 },
        {
          file: 'featured_item/ichi-japan-xuat-khau-lao-dong-nhat-ban-luong-cao-chi-phi-thap/index.html',
          line: 754,
        },
        {
          file: 'featured_item/xanhthienthanh-cong-ty-co-phan-dau-tu-va-phat-trien-xanh-thien-thanh/index.html',
          line: 755,
        },
        {
          file: 'featured_item/cinvico-lean-pro-cong-ty-co-phan-hop-tac-dau-tu-cong-nghe-cinvico/index.html',
          line: 755,
        },
        {
          file: 'featured_item/wewell-cong-ty-co-phan-duoc-lieu-va-thuc-pham-viet-nam/index.html',
          line: 755,
        },
        { file: 'featured_item/giang-lam-dung-cu-co-khi/index.html', line: 755 },
        { file: 'featured_item/wisdomland-international-preschool/index.html', line: 754 },
        { file: 'featured_item/forex-robot-automated-trading-robots/index.html', line: 754 },
        {
          file: 'featured_item/hoang-gia-cong-ty-cp-xay-dung-va-noi-that-hoang-gia/index.html',
          line: 755,
        },
        { file: 'featured_item/moonstore-thoi-trang-cong-so-moonstore/index.html', line: 755 },
        {
          file: 'featured_item/nutrition-fitness-cong-ty-co-phan-nutrition-fitness/index.html',
          line: 755,
        },
        {
          file: 'featured_item/binh-phat-cong-ty-tnhh-may-xay-dung-binh-phat/index.html',
          line: 755,
        },
        {
          file: 'featured_item/hung-an-group-dich-vu-cung-ung-nhan-luc-uy-tin-nhat/index.html',
          line: 755,
        },
        {
          file: 'featured_item/sua-tivi-chuyen-nghiep-dich-vu-sua-chua-tivi-thiet-bi-am-thanh-chinh-hang/index.html',
          line: 755,
        },
        { file: 'featured_item/weha-dua-cong-nghe-gan-gui-hon-voi-doi-song/index.html', line: 755 },
        {
          file: 'featured_item/novopharm-tan-tam-cho-su-sang-tao-chat-luong/index.html',
          line: 755,
        },
        {
          file: 'featured_item/applesmile-cua-hang-san-pham-apple-chinh-hang/index.html',
          line: 755,
        },
        { file: 'featured_item/tengroup-all-for-the-best/index.html', line: 755 },
        { file: 'featured_item/banh-nuong-an-vat-co-ti/index.html', line: 755 },
        {
          file: 'featured_item/an-phat-cong-ty-co-phan-cong-nghe-thuong-mai-an-phat/index.html',
          line: 755,
        },
        { file: 'featured_item/nikico-cong-ty-tnhh-nihon-kizai/index.html', line: 755 },
        { file: 'featured_item/dwatch-luxury-dong-ho-thuy-sy/index.html', line: 755 },
        {
          file: 'featured_item/drnhanh-cong-ty-tnhh-tu-van-giao-duc-dr-nhanh/index.html',
          line: 755,
        },
        {
          file: 'featured_item/hoanglan-logistics-don-vi-van-chuyen-hang-trung-viet-hang-dau-viet-nam/index.html',
          line: 755,
        },
        { file: 'featured_item/hop-hao-huc-cong-ty-tnhh-mam-nho/index.html', line: 755 },
        { file: 'featured_item/cong-ty-cp-dau-tu-xay-dung-vina2/index.html', line: 755 },
        {
          file: 'featured_item/cong-ty-cp-du-lich-thuong-mai-khung-troi-viet/index.html',
          line: 755,
        },
        { file: 'featured_item/cong-ty-tnhh-son-nero-thuong-hieu-modena/index.html', line: 755 },
        {
          file: 'featured_item/trangmoon-shop-cay-canh-de-ban-hop-phong-thuy/index.html',
          line: 755,
        },
        {
          file: 'featured_item/pro-car-parts-viet-nam-phan-phoi-phu-tung-bao-duong-gam-o-to/index.html',
          line: 755,
        },
        {
          file: 'featured_item/ppmvn-cong-ty-tnhh-quan-ly-tai-san-premier-viet-nam/index.html',
          line: 755,
        },
        {
          file: 'featured_item/viet-tht-production-cong-ty-co-phan-viet-tht/index.html',
          line: 755,
        },
        {
          file: 'featured_item/lien-doan-thuong-mai-va-cong-nghiep-viet-nam-tai-da-nang-vcci-da-nang/index.html',
          line: 755,
        },
        { file: 'featured_item/pa-store-cong-ty-tnhh-pa-marketing/index.html', line: 755 },
        { file: 'featured_item/cong-ty-luat-legal-art/index.html', line: 755 },
        { file: 'featured_item/cong-ty-tnhh-nha-khoa-viva-dental/index.html', line: 755 },
        { file: 'featured_item/nha-khoa-tham-my-quoc-te-viet-phap/index.html', line: 755 },
        {
          file: 'featured_item/cong-ty-cp-cong-nghe-an-ninh-mang-quoc-gia-viet-nam/index.html',
          line: 755,
        },
        { file: 'featured_item/hrzone-kien-tao-cong-dong-nhan-su-quoc-te/index.html', line: 755 },
        {
          file: 'featured_item/tintuc365-cong-ty-co-phan-truyen-thong-thuong-mai-viet/index.html',
          line: 755,
        },
        { file: 'featured_item/an-phu-decor-kien-tao-giac-mo/index.html', line: 755 },
        { file: 'featured_item/aya-spa-beauty-cong-ty-co-phan-go-do/index.html', line: 755 },
        { file: 'featured_item/truong-trung-hoc-pho-thong-huynh-thuc-khang/index.html', line: 755 },
        { file: 'featured_item/stormick-cong-ty-tnhh-storm-entertaiment/index.html', line: 755 },
        {
          file: 'featured_item/giao-dien-dsmart-giai-phap-dieu-khien-xe-hoi-tren-smartphone/index.html',
          line: 755,
        },
      ],
    },
  },
  {
    id: 'project-terms-2',
    body: {
      format: 'sanitized-html',
      html: '<h2><strong>HÌNH THỨC THANH TOÁN:</strong></h2> <strong>Lần 1:</strong> 50% sau khi ký hợp đồng. <strong>Lần 2:</strong> 50% khi nhận bàn giao website <h2><strong>THỜI GIAN THỰC HIỆN:</strong></h2> Lên giao diện Demo trong vòng: 7 – 10 ngày Tiến hành lập trình: 15 – 20 ngày <strong>Lưu ý:</strong> Thời gian chỉ mang tính chất tham khảo, trong quá trình làm cần có sự thống nhất 2 bên để tiến độ Web sẽ sớm hoàn thành. <h2><strong>THỜI GIAN BẢO HÀNH:</strong></h2> Bảo hành website <strong>vĩnh viễn</strong> trong trường hợp khách hàng sử dụng Hosting tại <strong>Sova</strong> Bảo hành <strong>1 năm</strong> đối với khách hàng sử dụng Hosting tại đơn vị khác. Hỗ trợ khách hàng miễn phí trong quá trình sử dụng website. <h2><strong>BÀN GIAO WESITE:</strong></h2> Website hoàn chỉnh theo mẫu Bản thiết kế website Admin quản trị website Thông tin hướng dẫn quản trị website',
      assetIds: [],
      sources: [
        {
          file: 'featured_item/nha-khoa-viva-dental-he-thong-chuoi-nha-khoa-tieu-chuan-my-dau-tien-tai-viet-nam/index.html',
          line: 755,
        },
        {
          file: 'featured_item/nha-khoa-viet-phap-he-thong-chuoi-nha-khoa-tieu-chuan-phap-dau-tien-tai-viet-nam/index.html',
          line: 755,
        },
        { file: 'featured_item/beework-cong-ty-tnhh-beework-viet-nam/index.html', line: 755 },
        { file: 'featured_item/cong-ty-co-phan-square-orange/index.html', line: 755 },
        { file: 'featured_item/cong-ty-tnhh-konnertec-viet-nam/index.html', line: 755 },
        { file: 'featured_item/so-y-te-benh-vien-mat-ha-giang/index.html', line: 755 },
        { file: 'featured_item/sencom-home-decor-lighting-design/index.html', line: 755 },
        { file: 'featured_item/flexius-cong-ty-co-phan-the-gioi-bang/index.html', line: 755 },
        { file: 'featured_item/cong-ty-co-phan-phat-trien-cong-nghe-thp/index.html', line: 755 },
      ],
    },
  },
];
