// Generated by scripts/import (npm run import) — do not edit.
import type { ListingSettings, ListingSnapshot } from '@/types/content';

export const listingSettings: ListingSettings[] = [
  {
    routeId: 'route-creative-branding',
    heading: { title: 'Creative Branding' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-en--insight',
    heading: { title: 'Insight' },
    hero: { headingLines: ['Insight'] },
  },
  {
    routeId: 'route-goc-nhin-website',
    heading: { title: 'Góc nhìn website' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-goc-nhin',
    heading: { title: 'Góc nhìn' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-goc-nhin--page--2',
    heading: { title: 'Góc nhìn' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-goc-nhin--page--3',
    heading: { title: 'Góc nhìn' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-goc-nhin--page--4',
    heading: { title: 'Góc nhìn' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-goc-nhin--page--5',
    heading: { title: 'Góc nhìn' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-social-marketing',
    heading: { title: 'Social Marketing' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-social-marketing--page--2',
    heading: { title: 'Social Marketing' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-thu-thuat',
    heading: { title: 'Thủ thuật' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-thu-thuat--page--2',
    heading: { title: 'Thủ thuật' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  { routeId: 'route-tin-tuc', heading: { title: 'Tin tức' }, hero: { headingLines: ['Góc nhìn'] } },
  { routeId: 'route-ux-ui', heading: { title: 'UX/UI' }, hero: { headingLines: ['Góc nhìn'] } },
  {
    routeId: 'route-du-an',
    heading: { title: 'Dự án đồng hành cùng Sova' },
    hero: { headingLines: ['Dự án đồng hành', 'cùng Sova'] },
  },
  {
    routeId: 'route-en--our-project',
    heading: { title: 'Projects Partnered with Sova' },
    hero: { headingLines: ['Projects Partnered', 'with Sova'] },
  },
  {
    routeId: 'route-featured_item',
    heading: { title: 'Dự án đồng hành cùng Sova' },
    hero: { headingLines: ['Dự án đồng hành', 'cùng Sova'] },
  },
  {
    routeId: 'route-featured_item_category--branding',
    heading: { title: 'Dự án đồng hành cùng Sova' },
    hero: { headingLines: ['Dự án đồng hành', 'cùng Sova'] },
  },
  {
    routeId: 'route-featured_item_category--mobile-app',
    heading: { title: 'Dự án đồng hành cùng Sova' },
    hero: { headingLines: ['Dự án đồng hành', 'cùng Sova'] },
  },
  {
    routeId: 'route-featured_item_category--website',
    heading: { title: 'Dự án đồng hành cùng Sova' },
    hero: { headingLines: ['Dự án đồng hành', 'cùng Sova'] },
  },
];
export const listingSnapshots: ListingSnapshot[] = [
  {
    routeId: 'route-goc-nhin',
    page: 1,
    orderedIds: ['post-2515', 'post-2492', 'post-2475', 'post-2458', 'post-2434', 'post-2417'],
    nextPath: '/goc-nhin/page/2/',
  },
  {
    routeId: 'route-goc-nhin',
    page: 2,
    orderedIds: ['post-2396', 'post-2378', 'post-2366', 'post-2345', 'post-2331', 'post-2323'],
    previousPath: '/goc-nhin/',
    nextPath: '/goc-nhin/page/3/',
  },
  {
    routeId: 'route-goc-nhin',
    page: 3,
    orderedIds: ['post-2288', 'post-2274', 'post-888', 'post-875', 'post-867', 'post-859'],
    previousPath: '/goc-nhin/page/2/',
    nextPath: '/goc-nhin/page/4/',
  },
  {
    routeId: 'route-goc-nhin',
    page: 4,
    orderedIds: ['post-853', 'post-836', 'post-826', 'post-815', 'post-803', 'post-794'],
    previousPath: '/goc-nhin/page/3/',
    nextPath: '/goc-nhin/page/5/',
  },
  {
    routeId: 'route-goc-nhin',
    page: 5,
    orderedIds: ['post-783', 'post-776', 'post-768'],
    previousPath: '/goc-nhin/page/4/',
  },
  { routeId: 'route-creative-branding', page: 1, orderedIds: ['post-888'] },
  {
    routeId: 'route-goc-nhin-website',
    page: 1,
    orderedIds: ['post-2515', 'post-2458', 'post-2417', 'post-2331', 'post-867', 'post-836'],
  },
  {
    routeId: 'route-social-marketing',
    page: 1,
    orderedIds: ['post-2345', 'post-815', 'post-803', 'post-794', 'post-783', 'post-776'],
    nextPath: '/social-marketing/page/2/',
  },
  {
    routeId: 'route-social-marketing',
    page: 2,
    orderedIds: ['post-768'],
    previousPath: '/social-marketing/',
  },
  {
    routeId: 'route-thu-thuat',
    page: 1,
    orderedIds: ['post-2492', 'post-2475', 'post-2434', 'post-2396', 'post-2378', 'post-2366'],
    nextPath: '/thu-thuat/page/2/',
  },
  {
    routeId: 'route-thu-thuat',
    page: 2,
    orderedIds: ['post-2331', 'post-2288', 'post-2274', 'post-875', 'post-859', 'post-836'],
    previousPath: '/thu-thuat/',
  },
  { routeId: 'route-tin-tuc', page: 1, orderedIds: ['post-853', 'post-826', 'post-815'] },
  { routeId: 'route-ux-ui', page: 1, orderedIds: ['post-2492', 'post-2323'] },
];
