// Generated by scripts/import (npm run import) — do not edit.
import type { ListingSettings, ListingSnapshot } from '@/types/content';

export const listingSettings: ListingSettings[] = [];
export const listingSnapshots: ListingSnapshot[] = [
  {
    routeId: '/goc-nhin/',
    page: 1,
    orderedIds: ['post-2515', 'post-2492', 'post-2475', 'post-2458', 'post-2434', 'post-2417'],
    nextPath: '/goc-nhin/page/2/',
  },
  {
    routeId: '/goc-nhin/',
    page: 2,
    orderedIds: ['post-2396', 'post-2378', 'post-2366', 'post-2345', 'post-2331', 'post-2323'],
    previousPath: '/goc-nhin/',
    nextPath: '/goc-nhin/page/3/',
  },
  {
    routeId: '/goc-nhin/',
    page: 3,
    orderedIds: ['post-2288', 'post-2274', 'post-888', 'post-875', 'post-867', 'post-859'],
    previousPath: '/goc-nhin/page/2/',
    nextPath: '/goc-nhin/page/4/',
  },
  {
    routeId: '/goc-nhin/',
    page: 4,
    orderedIds: ['post-853', 'post-836', 'post-826', 'post-815', 'post-803', 'post-794'],
    previousPath: '/goc-nhin/page/3/',
    nextPath: '/goc-nhin/page/5/',
  },
  {
    routeId: '/goc-nhin/',
    page: 5,
    orderedIds: ['post-783', 'post-776', 'post-768'],
    previousPath: '/goc-nhin/page/4/',
  },
  { routeId: '/creative-branding/', page: 1, orderedIds: ['post-888'] },
  {
    routeId: '/goc-nhin-website/',
    page: 1,
    orderedIds: ['post-2515', 'post-2458', 'post-2417', 'post-2331', 'post-867', 'post-836'],
  },
  {
    routeId: '/social-marketing/',
    page: 1,
    orderedIds: ['post-2345', 'post-815', 'post-803', 'post-794', 'post-783', 'post-776'],
    nextPath: '/social-marketing/page/2/',
  },
  {
    routeId: '/social-marketing/',
    page: 2,
    orderedIds: ['post-768'],
    previousPath: '/social-marketing/',
  },
  {
    routeId: '/thu-thuat/',
    page: 1,
    orderedIds: ['post-2492', 'post-2475', 'post-2434', 'post-2396', 'post-2378', 'post-2366'],
    nextPath: '/thu-thuat/page/2/',
  },
  {
    routeId: '/thu-thuat/',
    page: 2,
    orderedIds: ['post-2331', 'post-2288', 'post-2274', 'post-875', 'post-859', 'post-836'],
    previousPath: '/thu-thuat/',
  },
  { routeId: '/tin-tuc/', page: 1, orderedIds: ['post-853', 'post-826', 'post-815'] },
  { routeId: '/ux-ui/', page: 1, orderedIds: ['post-2492', 'post-2323'] },
];
