// Generated by scripts/import (npm run import) — do not edit.
import type { ListingSettings, ListingSnapshot } from '@/types/content';

export const listingSettings: ListingSettings[] = [
  {
    routeId: 'route-creative-branding',
    heading: { title: 'Creative Branding' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-en--insight',
    heading: { title: 'Insight' },
    hero: { headingLines: ['Insight'] },
  },
  {
    routeId: 'route-goc-nhin-website',
    heading: { title: 'Góc nhìn website' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-goc-nhin',
    heading: { title: 'Góc nhìn' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-goc-nhin--page--2',
    heading: { title: 'Góc nhìn' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-goc-nhin--page--3',
    heading: { title: 'Góc nhìn' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-goc-nhin--page--4',
    heading: { title: 'Góc nhìn' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-goc-nhin--page--5',
    heading: { title: 'Góc nhìn' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-social-marketing',
    heading: { title: 'Social Marketing' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-social-marketing--page--2',
    heading: { title: 'Social Marketing' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-thu-thuat',
    heading: { title: 'Thủ thuật' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  {
    routeId: 'route-thu-thuat--page--2',
    heading: { title: 'Thủ thuật' },
    hero: { headingLines: ['Góc nhìn'] },
  },
  { routeId: 'route-tin-tuc', heading: { title: 'Tin tức' }, hero: { headingLines: ['Góc nhìn'] } },
  { routeId: 'route-ux-ui', heading: { title: 'UX/UI' }, hero: { headingLines: ['Góc nhìn'] } },
  {
    routeId: 'route-du-an',
    heading: { title: 'Dự án đồng hành cùng Sova' },
    hero: {
      headingLines: ['Dự án đồng hành', 'cùng Sova'],
      description: {
        format: 'sanitized-html',
        html: 'Khám phá tư duy thiết kế và triết lý sáng tạo được chúng tôi gửi gắm trong từng dự án.',
        assetIds: [],
        sources: [{ file: 'du-an/index.html', line: 709 }],
      },
      cta: { label: 'Kết nối ngay →', href: '/lien-he/' },
      imageId: 'asset-f85d3636d6',
      bgImageId: 'asset-40c494b5f4',
      breadcrumb: [{ label: 'Trang chủ', href: '/' }, { label: 'Dự án' }],
    },
  },
  {
    routeId: 'route-en--our-project',
    heading: { title: 'Projects Partnered with Sova' },
    hero: {
      headingLines: ['Projects Partnered', 'with Sova'],
      description: {
        format: 'sanitized-html',
        html: 'Explore the design mindset and creative philosophy that we embed in every project.',
        assetIds: [],
        sources: [{ file: 'en/our-project/index.html', line: 708 }],
      },
      cta: { label: 'Connect now →', href: '/lien-he/' },
      imageId: 'asset-f85d3636d6',
      bgImageId: 'asset-40c494b5f4',
      breadcrumb: [{ label: 'Home', href: '/' }, { label: 'Projects' }],
    },
  },
  {
    routeId: 'route-featured_item',
    heading: { title: 'Công ty Cổ phần Phát triển Công nghệ THP' },
    hero: {
      headingLines: ['Dự án đồng hành', 'cùng Sova'],
      description: {
        format: 'sanitized-html',
        html: 'Khám phá tư duy thiết kế và triết lý sáng tạo được chúng tôi gửi gắm trong từng dự án.',
        assetIds: [],
        sources: [{ file: 'featured_item/index.html', line: 709 }],
      },
      cta: { label: 'Kết nối ngay →', href: '/lien-he/' },
      imageId: 'asset-f85d3636d6',
      bgImageId: 'asset-40c494b5f4',
      breadcrumb: [{ label: 'Trang chủ', href: '/' }, { label: 'Dự án' }],
    },
  },
  {
    routeId: 'route-featured_item_category--branding',
    heading: { title: 'Branding' },
    hero: {
      headingLines: ['Dự án đồng hành', 'cùng Sova'],
      description: {
        format: 'sanitized-html',
        html: 'Khám phá tư duy thiết kế và triết lý sáng tạo được chúng tôi gửi gắm trong từng dự án.',
        assetIds: [],
        sources: [{ file: 'featured_item_category/branding/index.html', line: 707 }],
      },
      cta: { label: 'Kết nối ngay →', href: '/lien-he/' },
      imageId: 'asset-f85d3636d6',
      bgImageId: 'asset-40c494b5f4',
      breadcrumb: [{ label: 'Trang chủ', href: '/' }, { label: 'Dự án' }],
    },
  },
  {
    routeId: 'route-featured_item_category--mobile-app',
    heading: { title: 'Mobile App' },
    hero: {
      headingLines: ['Dự án đồng hành', 'cùng Sova'],
      description: {
        format: 'sanitized-html',
        html: 'Khám phá tư duy thiết kế và triết lý sáng tạo được chúng tôi gửi gắm trong từng dự án.',
        assetIds: [],
        sources: [{ file: 'featured_item_category/mobile-app/index.html', line: 707 }],
      },
      cta: { label: 'Kết nối ngay →', href: '/lien-he/' },
      imageId: 'asset-f85d3636d6',
      bgImageId: 'asset-40c494b5f4',
      breadcrumb: [{ label: 'Trang chủ', href: '/' }, { label: 'Dự án' }],
    },
  },
  {
    routeId: 'route-featured_item_category--website',
    heading: { title: 'Website' },
    hero: {
      headingLines: ['Dự án đồng hành', 'cùng Sova'],
      description: {
        format: 'sanitized-html',
        html: 'Khám phá tư duy thiết kế và triết lý sáng tạo được chúng tôi gửi gắm trong từng dự án.',
        assetIds: [],
        sources: [{ file: 'featured_item_category/website/index.html', line: 708 }],
      },
      cta: { label: 'Kết nối ngay →', href: '/lien-he/' },
      imageId: 'asset-f85d3636d6',
      bgImageId: 'asset-40c494b5f4',
      breadcrumb: [{ label: 'Trang chủ', href: '/' }, { label: 'Dự án' }],
    },
  },
];
export const listingSnapshots: ListingSnapshot[] = [
  {
    routeId: 'route-goc-nhin',
    page: 1,
    orderedIds: ['post-2515', 'post-2492', 'post-2475', 'post-2458', 'post-2434', 'post-2417'],
    nextPath: '/goc-nhin/page/2/',
  },
  {
    routeId: 'route-goc-nhin',
    page: 2,
    orderedIds: ['post-2396', 'post-2378', 'post-2366', 'post-2345', 'post-2331', 'post-2323'],
    previousPath: '/goc-nhin/',
    nextPath: '/goc-nhin/page/3/',
  },
  {
    routeId: 'route-goc-nhin',
    page: 3,
    orderedIds: ['post-2288', 'post-2274', 'post-888', 'post-875', 'post-867', 'post-859'],
    previousPath: '/goc-nhin/page/2/',
    nextPath: '/goc-nhin/page/4/',
  },
  {
    routeId: 'route-goc-nhin',
    page: 4,
    orderedIds: ['post-853', 'post-836', 'post-826', 'post-815', 'post-803', 'post-794'],
    previousPath: '/goc-nhin/page/3/',
    nextPath: '/goc-nhin/page/5/',
  },
  {
    routeId: 'route-goc-nhin',
    page: 5,
    orderedIds: ['post-783', 'post-776', 'post-768'],
    previousPath: '/goc-nhin/page/4/',
  },
  { routeId: 'route-creative-branding', page: 1, orderedIds: ['post-888'] },
  {
    routeId: 'route-goc-nhin-website',
    page: 1,
    orderedIds: ['post-2515', 'post-2458', 'post-2417', 'post-2331', 'post-867', 'post-836'],
  },
  {
    routeId: 'route-social-marketing',
    page: 1,
    orderedIds: ['post-2345', 'post-815', 'post-803', 'post-794', 'post-783', 'post-776'],
    nextPath: '/social-marketing/page/2/',
  },
  {
    routeId: 'route-social-marketing',
    page: 2,
    orderedIds: ['post-768'],
    previousPath: '/social-marketing/',
  },
  {
    routeId: 'route-thu-thuat',
    page: 1,
    orderedIds: ['post-2492', 'post-2475', 'post-2434', 'post-2396', 'post-2378', 'post-2366'],
    nextPath: '/thu-thuat/page/2/',
  },
  {
    routeId: 'route-thu-thuat',
    page: 2,
    orderedIds: ['post-2331', 'post-2288', 'post-2274', 'post-875', 'post-859', 'post-836'],
    previousPath: '/thu-thuat/',
  },
  { routeId: 'route-tin-tuc', page: 1, orderedIds: ['post-853', 'post-826', 'post-815'] },
  { routeId: 'route-ux-ui', page: 1, orderedIds: ['post-2492', 'post-2323'] },
];

export const blogListingCopy = {
  vi: {
    title: 'Góc nhìn',
    breadcrumbHome: 'Trang chủ',
    breadcrumbBlog: 'Góc nhìn',
    readMore: 'Đọc tiếp →',
    searchTitle: 'Tìm kiếm',
    categoriesTitle: 'Danh mục bài viết',
    searchPlaceholder: 'Search…',
    searchSubmit: 'Gửi',
    pagination: {
      nav: 'Phân trang bài viết',
      prev: 'Trang trước',
      next: 'Trang tiếp theo',
    },
  },
  en: {
    title: 'Insight',
    breadcrumbHome: 'Home',
    breadcrumbBlog: 'Insight',
    readMore: 'Read more →',
    searchTitle: 'Search',
    categoriesTitle: 'Categories',
    searchPlaceholder: 'Search…',
    searchSubmit: 'Submit',
    pagination: {
      nav: 'Post pagination',
      prev: 'Previous page',
      next: 'Next page',
    },
  },
};

export const blogDetailCopy = {
  breadcrumbHome: 'Trang chủ',
  breadcrumbBlog: 'Góc nhìn',
  breadcrumbCurrent: 'Chi tiết',
  headingBackgroundImage: '/wp-content/uploads/2024/03/ec9c55cfcb4d0c64ecafd52d957c13e9.png',
  relatedTitle: 'Bài viết liên quan:',
};

export const projectListingCopy = {
  vi: {
    filterAll: 'Tất cả',
    emptyMessage: 'Không có dự án nào.',
    loadingMessage: 'Đang tải...',
    pagination: {
      nav: 'Phân trang dự án',
      prev: 'Trang trước',
      next: 'Trang tiếp theo',
    },
  },
  en: {
    filterAll: 'All',
    emptyMessage: 'No projects found.',
    loadingMessage: 'Đang tải...',
    pagination: {
      nav: 'Project pagination',
      prev: 'Previous page',
      next: 'Next page',
    },
  },
};
