// Generated by scripts/import (npm run import) — do not edit.
import type { Navigation } from '@/types/content';

export const navigation: Navigation[] = [
  {
    locale: 'vi',
    header: [
      {
        id: 'nav-header-vi-root',
        label: 'Trang chủ',
        destination: { kind: 'internal', routeId: 'route-root' },
      },
      {
        id: 'nav-header-vi-gioi-thieu',
        label: 'Giới thiệu',
        destination: { kind: 'internal', routeId: 'route-gioi-thieu' },
      },
      {
        id: 'nav-header-vi-dich-vu',
        label: 'Dịch vụ',
        children: [
          {
            id: 'nav-header-vi-thiet-ke-website',
            label: 'Thiết kế website',
            destination: { kind: 'internal', routeId: 'route-thiet-ke-website' },
          },
          {
            id: 'nav-header-vi-thiet-ke-app-mobile',
            label: 'Thiết kế App Mobile',
            destination: { kind: 'internal', routeId: 'route-thiet-ke-app-mobile' },
          },
          {
            id: 'nav-header-vi-seo-tu-khoa-website',
            label: 'SEO từ khoá website',
            destination: { kind: 'internal', routeId: 'route-seo-tu-khoa-website' },
          },
          {
            id: 'nav-header-vi-ui-ux-branding-design',
            label: 'UI/UX, Branding Design',
            destination: { kind: 'internal', routeId: 'route-ui-ux-branding-design' },
          },
          {
            id: 'nav-header-vi-e-mail-doanh-nghiep',
            label: 'E-mail doanh nghiệp',
            destination: { kind: 'internal', routeId: 'route-e-mail-doanh-nghiep' },
          },
          {
            id: 'nav-header-vi-giai-phap-luu-tru',
            label: 'Giải pháp lưu trữ',
            destination: { kind: 'internal', routeId: 'route-giai-phap-luu-tru' },
            children: [
              {
                id: 'nav-header-vi-hosting-doanh-nghiep',
                label: 'Hosting doanh nghiệp',
                destination: { kind: 'internal', routeId: 'route-hosting-doanh-nghiep' },
              },
              {
                id: 'nav-header-vi-vps-doanh-nghiep',
                label: 'VPS Doanh nghiệp',
                destination: { kind: 'internal', routeId: 'route-vps-doanh-nghiep' },
              },
            ],
          },
        ],
      },
      {
        id: 'nav-header-vi-du-an',
        label: 'Dự án',
        destination: { kind: 'internal', routeId: 'route-du-an' },
      },
      {
        id: 'nav-header-vi-goc-nhin',
        label: 'Góc nhìn',
        destination: { kind: 'internal', routeId: 'route-goc-nhin' },
      },
    ],
    mobile: [
      {
        id: 'nav-header-vi-root',
        label: 'Trang chủ',
        destination: { kind: 'internal', routeId: 'route-root' },
      },
      {
        id: 'nav-header-vi-gioi-thieu',
        label: 'Giới thiệu',
        destination: { kind: 'internal', routeId: 'route-gioi-thieu' },
      },
      {
        id: 'nav-header-vi-dich-vu',
        label: 'Dịch vụ',
        children: [
          {
            id: 'nav-header-vi-thiet-ke-website',
            label: 'Thiết kế website',
            destination: { kind: 'internal', routeId: 'route-thiet-ke-website' },
          },
          {
            id: 'nav-header-vi-thiet-ke-app-mobile',
            label: 'Thiết kế App Mobile',
            destination: { kind: 'internal', routeId: 'route-thiet-ke-app-mobile' },
          },
          {
            id: 'nav-header-vi-seo-tu-khoa-website',
            label: 'SEO từ khoá website',
            destination: { kind: 'internal', routeId: 'route-seo-tu-khoa-website' },
          },
          {
            id: 'nav-header-vi-ui-ux-branding-design',
            label: 'UI/UX, Branding Design',
            destination: { kind: 'internal', routeId: 'route-ui-ux-branding-design' },
          },
          {
            id: 'nav-header-vi-e-mail-doanh-nghiep',
            label: 'E-mail doanh nghiệp',
            destination: { kind: 'internal', routeId: 'route-e-mail-doanh-nghiep' },
          },
          {
            id: 'nav-header-vi-giai-phap-luu-tru',
            label: 'Giải pháp lưu trữ',
            destination: { kind: 'internal', routeId: 'route-giai-phap-luu-tru' },
            children: [
              {
                id: 'nav-header-vi-hosting-doanh-nghiep',
                label: 'Hosting doanh nghiệp',
                destination: { kind: 'internal', routeId: 'route-hosting-doanh-nghiep' },
              },
              {
                id: 'nav-header-vi-vps-doanh-nghiep',
                label: 'VPS Doanh nghiệp',
                destination: { kind: 'internal', routeId: 'route-vps-doanh-nghiep' },
              },
            ],
          },
        ],
      },
      {
        id: 'nav-header-vi-du-an',
        label: 'Dự án',
        destination: { kind: 'internal', routeId: 'route-du-an' },
      },
      {
        id: 'nav-header-vi-goc-nhin',
        label: 'Góc nhìn',
        destination: { kind: 'internal', routeId: 'route-goc-nhin' },
      },
    ],
    footerGroups: [
      {
        id: 'footer-about',
        label: 'VỀ CHÚNG TÔI',
        items: [
          {
            id: 'nav-footer-vi-root',
            label: 'Trang chủ',
            destination: { kind: 'internal', routeId: 'route-root' },
          },
          {
            id: 'nav-footer-vi-gioi-thieu',
            label: 'Giới thiệu',
            destination: { kind: 'internal', routeId: 'route-gioi-thieu' },
          },
          {
            id: 'nav-footer-vi-du-an',
            label: 'Dự án',
            destination: { kind: 'internal', routeId: 'route-du-an' },
          },
          {
            id: 'nav-footer-vi-goc-nhin',
            label: 'Góc nhìn',
            destination: { kind: 'internal', routeId: 'route-goc-nhin' },
          },
          {
            id: 'nav-footer-vi-lien-he',
            label: 'Liên hệ',
            destination: { kind: 'internal', routeId: 'route-lien-he' },
          },
        ],
      },
      {
        id: 'footer-service',
        label: 'DỊCH VỤ',
        items: [
          {
            id: 'nav-footer-vi-thiet-ke-website',
            label: 'Thiết kế website',
            destination: { kind: 'internal', routeId: 'route-thiet-ke-website' },
          },
          {
            id: 'nav-footer-vi-thiet-ke-app-mobile',
            label: 'Thiết kế App mobile',
            destination: { kind: 'internal', routeId: 'route-thiet-ke-app-mobile' },
          },
          {
            id: 'nav-footer-vi-seo-tu-khoa-website',
            label: 'SEO từ khoá website',
            destination: { kind: 'internal', routeId: 'route-seo-tu-khoa-website' },
          },
          {
            id: 'nav-footer-vi-ui-ux-branding-design',
            label: 'UI/UX, Branding Design',
            destination: { kind: 'internal', routeId: 'route-ui-ux-branding-design' },
          },
          {
            id: 'nav-footer-vi-e-mail-doanh-nghiep',
            label: 'E-mail doanh nghiệp',
            destination: { kind: 'internal', routeId: 'route-e-mail-doanh-nghiep' },
          },
          {
            id: 'nav-footer-vi-giai-phap-luu-tru',
            label: 'Giải pháp lưu trữ',
            destination: { kind: 'internal', routeId: 'route-giai-phap-luu-tru' },
          },
        ],
      },
      {
        id: 'footer-quick-links',
        label: 'LIÊN KẾT NHANH',
        items: [
          {
            id: 'nav-footer-vi-cau-hoi-thuong-gap',
            label: 'Câu hỏi thường gặp',
            destination: { kind: 'internal', routeId: 'route-cau-hoi-thuong-gap' },
          },
          {
            id: 'nav-footer-vi-dieu-khoan-su-dung',
            label: 'Điều khoản sử dụng',
            destination: { kind: 'internal', routeId: 'route-dieu-khoan-su-dung' },
          },
          {
            id: 'nav-footer-vi-chinh-sach-bao-mat',
            label: 'Chính sách bảo mật',
            destination: { kind: 'internal', routeId: 'route-chinh-sach-bao-mat' },
          },
          {
            id: 'nav-footer-vi-chinh-sach-hoan-tien',
            label: 'Chính sách hoàn tiền',
            destination: { kind: 'internal', routeId: 'route-chinh-sach-hoan-tien' },
          },
          {
            id: 'nav-footer-vi-chinh-sach-bao-hanh',
            label: 'Chính sách bảo hành',
            destination: { kind: 'internal', routeId: 'route-chinh-sach-bao-hanh' },
          },
          {
            id: 'nav-footer-vi-huong-dan-thanh-toan',
            label: 'Hướng dẫn thanh toán',
            destination: { kind: 'internal', routeId: 'route-huong-dan-thanh-toan' },
          },
        ],
      },
    ],
    serviceOptions: [
      {
        id: 'nav-service-option-vi-thiet-ke-website',
        label: 'Dịch Vụ Thiết Kế Website',
        destination: { kind: 'internal', routeId: 'route-thiet-ke-website' },
      },
      {
        id: 'nav-service-option-vi-thiet-ke-app-mobile',
        label: 'Dịch Vụ Thiết Kế App Mobile',
        destination: { kind: 'internal', routeId: 'route-thiet-ke-app-mobile' },
      },
      {
        id: 'nav-service-option-vi-seo-tu-khoa-website',
        label: 'Dịch Vụ SEO Từ Khoá Website',
        destination: { kind: 'internal', routeId: 'route-seo-tu-khoa-website' },
      },
      {
        id: 'nav-service-option-vi-ui-ux-branding-design',
        label: 'Dịch Vụ UI/UX, Branding Design',
        destination: { kind: 'internal', routeId: 'route-ui-ux-branding-design' },
      },
      {
        id: 'nav-service-option-vi-giai-phap-luu-tru',
        label: 'Dịch Vụ Giải Pháp Lưu Trữ',
        destination: { kind: 'internal', routeId: 'route-giai-phap-luu-tru' },
      },
      {
        id: 'nav-service-option-vi-e-mail-doanh-nghiep',
        label: 'Dịch Vụ E-mail Doanh Nghiệp',
        destination: { kind: 'internal', routeId: 'route-e-mail-doanh-nghiep' },
      },
    ],
  },
  {
    locale: 'en',
    header: [
      {
        id: 'nav-header-en-en--home',
        label: 'Home',
        destination: { kind: 'internal', routeId: 'route-en--home' },
      },
      {
        id: 'nav-header-en-en--about-us',
        label: 'About Us',
        destination: { kind: 'internal', routeId: 'route-en--about-us' },
      },
      {
        id: 'nav-header-en-services',
        label: 'Services',
        children: [
          {
            id: 'nav-header-en-en--website-development',
            label: 'Website Development',
            destination: { kind: 'internal', routeId: 'route-en--website-development' },
          },
          {
            id: 'nav-header-en-en--app-mobile-development',
            label: 'App Mobile Development',
            destination: { kind: 'internal', routeId: 'route-en--app-mobile-development' },
          },
          {
            id: 'nav-header-en-en--website-keyword-seo',
            label: 'Website Keyword SEO',
            destination: { kind: 'internal', routeId: 'route-en--website-keyword-seo' },
          },
          {
            id: 'nav-header-en-en--ui-ux-branding-design-2',
            label: 'UI/UX, Branding Design',
            destination: { kind: 'internal', routeId: 'route-en--ui-ux-branding-design-2' },
          },
          {
            id: 'nav-header-en-en--business-e-mail',
            label: 'Business E-mail',
            destination: { kind: 'internal', routeId: 'route-en--business-e-mail' },
          },
          {
            id: 'nav-header-en-en--storage-solution',
            label: 'Storage Solution',
            destination: { kind: 'internal', routeId: 'route-en--storage-solution' },
            children: [
              {
                id: 'nav-header-en-en--business-hosting',
                label: 'Business Hosting',
                destination: { kind: 'internal', routeId: 'route-en--business-hosting' },
              },
              {
                id: 'nav-header-en-en--business-vps',
                label: 'Business VPS',
                destination: { kind: 'internal', routeId: 'route-en--business-vps' },
              },
            ],
          },
        ],
      },
      {
        id: 'nav-header-en-en--our-project',
        label: 'Our Project',
        destination: { kind: 'internal', routeId: 'route-en--our-project' },
      },
      {
        id: 'nav-header-en-en--insight',
        label: 'Insight',
        destination: { kind: 'internal', routeId: 'route-en--insight' },
      },
    ],
    mobile: [
      {
        id: 'nav-header-en-en--home',
        label: 'Home',
        destination: { kind: 'internal', routeId: 'route-en--home' },
      },
      {
        id: 'nav-header-en-en--about-us',
        label: 'About Us',
        destination: { kind: 'internal', routeId: 'route-en--about-us' },
      },
      {
        id: 'nav-header-en-services',
        label: 'Services',
        children: [
          {
            id: 'nav-header-en-en--website-development',
            label: 'Website Development',
            destination: { kind: 'internal', routeId: 'route-en--website-development' },
          },
          {
            id: 'nav-header-en-en--app-mobile-development',
            label: 'App Mobile Development',
            destination: { kind: 'internal', routeId: 'route-en--app-mobile-development' },
          },
          {
            id: 'nav-header-en-en--website-keyword-seo',
            label: 'Website Keyword SEO',
            destination: { kind: 'internal', routeId: 'route-en--website-keyword-seo' },
          },
          {
            id: 'nav-header-en-en--ui-ux-branding-design-2',
            label: 'UI/UX, Branding Design',
            destination: { kind: 'internal', routeId: 'route-en--ui-ux-branding-design-2' },
          },
          {
            id: 'nav-header-en-en--business-e-mail',
            label: 'Business E-mail',
            destination: { kind: 'internal', routeId: 'route-en--business-e-mail' },
          },
          {
            id: 'nav-header-en-en--storage-solution',
            label: 'Storage Solution',
            destination: { kind: 'internal', routeId: 'route-en--storage-solution' },
            children: [
              {
                id: 'nav-header-en-en--business-hosting',
                label: 'Business Hosting',
                destination: { kind: 'internal', routeId: 'route-en--business-hosting' },
              },
              {
                id: 'nav-header-en-en--business-vps',
                label: 'Business VPS',
                destination: { kind: 'internal', routeId: 'route-en--business-vps' },
              },
            ],
          },
        ],
      },
      {
        id: 'nav-header-en-en--our-project',
        label: 'Our Project',
        destination: { kind: 'internal', routeId: 'route-en--our-project' },
      },
      {
        id: 'nav-header-en-en--insight',
        label: 'Insight',
        destination: { kind: 'internal', routeId: 'route-en--insight' },
      },
    ],
    footerGroups: [
      {
        id: 'footer-about',
        label: 'ABOUT US',
        items: [
          {
            id: 'nav-footer-en-en--home',
            label: 'Home',
            destination: { kind: 'internal', routeId: 'route-en--home' },
          },
          {
            id: 'nav-footer-en-en--about-us',
            label: 'About us',
            destination: { kind: 'internal', routeId: 'route-en--about-us' },
          },
          {
            id: 'nav-footer-en-en--our-project',
            label: 'Our Project',
            destination: { kind: 'internal', routeId: 'route-en--our-project' },
          },
          {
            id: 'nav-footer-en-en--insight',
            label: 'Insights',
            destination: { kind: 'internal', routeId: 'route-en--insight' },
          },
          {
            id: 'nav-footer-en-en--contact-us',
            label: 'Contact Us',
            destination: { kind: 'internal', routeId: 'route-en--contact-us' },
          },
        ],
      },
      {
        id: 'footer-service',
        label: 'SERVICE',
        items: [
          {
            id: 'nav-footer-en-en--website-development',
            label: 'Website Development',
            destination: { kind: 'internal', routeId: 'route-en--website-development' },
          },
          {
            id: 'nav-footer-en-en--app-mobile-development',
            label: 'App Mobile Development',
            destination: { kind: 'internal', routeId: 'route-en--app-mobile-development' },
          },
          {
            id: 'nav-footer-en-en--website-keyword-seo',
            label: 'Website Keyword SEO',
            destination: { kind: 'internal', routeId: 'route-en--website-keyword-seo' },
          },
          {
            id: 'nav-footer-en-en--ui-ux-branding-design-2',
            label: 'UX/UI, Branding Design',
            destination: { kind: 'internal', routeId: 'route-en--ui-ux-branding-design-2' },
          },
          {
            id: 'nav-footer-en-en--business-e-mail',
            label: 'Business E-mail',
            destination: { kind: 'internal', routeId: 'route-en--business-e-mail' },
          },
          {
            id: 'nav-footer-en-en--storage-solution',
            label: 'Storage Solution',
            destination: { kind: 'internal', routeId: 'route-en--storage-solution' },
          },
        ],
      },
      {
        id: 'footer-quick-links',
        label: 'QUICK LINKS',
        items: [
          {
            id: 'nav-footer-en-en--faq',
            label: 'FAQ',
            destination: { kind: 'internal', routeId: 'route-en--faq' },
          },
          {
            id: 'nav-footer-en-en--terms-of-use',
            label: 'Term of use',
            destination: { kind: 'internal', routeId: 'route-en--terms-of-use' },
          },
          {
            id: 'nav-footer-en-chinh-sach-bao-mat',
            label: 'Privacy Policy',
            destination: { kind: 'internal', routeId: 'route-chinh-sach-bao-mat' },
          },
          {
            id: 'nav-footer-en-en--refund-policy',
            label: 'Refund Policy',
            destination: { kind: 'internal', routeId: 'route-en--refund-policy' },
          },
          {
            id: 'nav-footer-en-en--warranty-policy',
            label: 'Warranty Policy',
            destination: { kind: 'internal', routeId: 'route-en--warranty-policy' },
          },
          {
            id: 'nav-footer-en-en--payment-guide',
            label: 'Payment Intructions',
            destination: { kind: 'internal', routeId: 'route-en--payment-guide' },
          },
        ],
      },
    ],
    serviceOptions: [
      {
        id: 'nav-service-option-en-en--website-development',
        label: 'Website Development',
        destination: { kind: 'internal', routeId: 'route-en--website-development' },
      },
      {
        id: 'nav-service-option-en-en--app-mobile-development',
        label: 'App Mobile Development',
        destination: { kind: 'internal', routeId: 'route-en--app-mobile-development' },
      },
      {
        id: 'nav-service-option-en-en--website-keyword-seo',
        label: 'Website Keyword SEO',
        destination: { kind: 'internal', routeId: 'route-en--website-keyword-seo' },
      },
      {
        id: 'nav-service-option-en-en--ui-ux-branding-design-2',
        label: 'UI/UX, Branding Design',
        destination: { kind: 'internal', routeId: 'route-en--ui-ux-branding-design-2' },
      },
      {
        id: 'nav-service-option-en-en--business-e-mail',
        label: 'Business E-mail',
        destination: { kind: 'internal', routeId: 'route-en--business-e-mail' },
      },
      {
        id: 'nav-service-option-en-en--storage-solution',
        label: 'Storage Solution',
        destination: { kind: 'internal', routeId: 'route-en--storage-solution' },
      },
    ],
  },
];
