// Generated by scripts/import (npm run import) — do not edit.
import type { PostCategory, SourceRef } from '@/types/content';

export const postCategories: (PostCategory & { sources: SourceRef[] })[] = [
  {
    id: 'post-category-creative-branding',
    locale: 'vi',
    slug: 'creative-branding',
    title: 'Creative Branding',
    path: '/creative-branding/',
    sourceDisplayCount: 1,
    sources: [{ file: 'goc-nhin/index.html', line: 766, sourceId: 'creative-branding' }],
  },
  {
    id: 'post-category-goc-nhin-website',
    locale: 'vi',
    slug: 'goc-nhin-website',
    title: 'Góc nhìn website',
    path: '/goc-nhin-website/',
    sourceDisplayCount: 6,
    sources: [{ file: 'goc-nhin/index.html', line: 768, sourceId: 'goc-nhin-website' }],
  },
  {
    id: 'post-category-social-marketing',
    locale: 'vi',
    slug: 'social-marketing',
    title: 'Social Marketing',
    path: '/social-marketing/',
    sourceDisplayCount: 7,
    sources: [{ file: 'goc-nhin/index.html', line: 770, sourceId: 'social-marketing' }],
  },
  {
    id: 'post-category-thu-thuat',
    locale: 'vi',
    slug: 'thu-thuat',
    title: 'Thủ thuật',
    path: '/thu-thuat/',
    sourceDisplayCount: 12,
    sources: [{ file: 'goc-nhin/index.html', line: 772, sourceId: 'thu-thuat' }],
  },
  {
    id: 'post-category-tin-tuc',
    locale: 'vi',
    slug: 'tin-tuc',
    title: 'Tin tức',
    path: '/tin-tuc/',
    sourceDisplayCount: 3,
    sources: [{ file: 'goc-nhin/index.html', line: 774, sourceId: 'tin-tuc' }],
  },
  {
    id: 'post-category-ux-ui',
    locale: 'vi',
    slug: 'ux-ui',
    title: 'UX/UI',
    path: '/ux-ui/',
    sourceDisplayCount: 2,
    sources: [{ file: 'goc-nhin/index.html', line: 776, sourceId: 'ux-ui' }],
  },
];
