// Generated by scripts/import (npm run import) — do not edit.
import type { ProjectCategory, SourceRef } from '@/types/content';

export const projectCategories: (ProjectCategory & { sources: SourceRef[] })[] = [
  {
    id: 'project-category-website',
    slug: 'website',
    label: 'Website',
    locale: 'vi',
    path: '/featured_item_category/website/',
    sources: [{ file: 'du-an/index.html', line: 850, sourceId: 'website' }],
  },
  {
    id: 'project-category-branding',
    slug: 'branding',
    label: 'Branding',
    locale: 'vi',
    path: '/featured_item_category/branding/',
    sources: [{ file: 'du-an/index.html', line: 848, sourceId: 'branding' }],
  },
  {
    id: 'project-category-mobile-app',
    slug: 'mobile-app',
    label: 'Mobile App',
    locale: 'vi',
    path: '/featured_item_category/mobile-app/',
    sources: [{ file: 'du-an/index.html', line: 849, sourceId: 'mobile-app' }],
  },
];
