// Generated by scripts/import (npm run import) — do not edit.
import type { Stat } from '@/types/content';

export const stats: Stat[] = [
  { id: 'stat-clients-vi', value: 3500, suffix: '+', label: 'Khách hàng hài lòng' },
  { id: 'stat-projects-vi', value: 1500, suffix: '+', label: 'Dự án hoàn thành' },
  { id: 'stat-members-vi', value: 40, suffix: '+', label: 'Thành viên' },
  { id: 'stat-years-vi', value: 9, suffix: '+', label: 'Năm kinh nghiệm' },
  { id: 'stat-clients-en', value: 3500, suffix: '+', label: 'Satisfied Clients' },
  { id: 'stat-projects-en', value: 1500, suffix: '+', label: 'Projects Completed' },
  { id: 'stat-members-en', value: 40, suffix: '+', label: 'Team members' },
  { id: 'stat-years-en', value: 9, suffix: '+', label: 'Years of experience' },
];
