// Generated by scripts/import (npm run import) — do not edit.
import type { Testimonial } from '@/types/content';

export const testimonials: Testimonial[] = [
  {
    id: 'testimonial-feedback-ten',
    locale: 'vi',
    person: 'Anh Bình',
    quote: {
      format: 'sanitized-html',
      html: 'Tôi đã tham khảo khá nhiều các đơn vị thiết kế website khác nhau, nhưng chỉ khi tới Sova, tôi mới quyết định hợp tác. Các bạn khiến tôi cảm thấy các bạn khác biệt, tận tâm, tự làm mọi thứ và rất lắng nghe.',
      assetIds: [],
      sources: [{ file: 'index.html', line: 2234 }],
    },
    sources: [{ file: 'index.html', line: 2226 }],
    role: 'TGD TEN Group',
    avatarId: 'asset-b6f667ae8f',
  },
  {
    id: 'testimonial-feedback-dong-a',
    locale: 'vi',
    person: 'ĐỖ MỸ LINH',
    quote: {
      format: 'sanitized-html',
      html: 'Là đối tác lâu năm với Sova, chúng tôi hoàn toàn tin tưởng để giao và triển khai các dự án phát triển sảm phẩm số đòi hỏi yêu cầu cao về trải nghiệm người dùng cho khách hàng và đối tác của mình.',
      assetIds: [],
      sources: [{ file: 'index.html', line: 2313 }],
    },
    sources: [{ file: 'index.html', line: 2305 }],
    role: 'Founder Bệnh viện thẩm mỹ Đông Á',
    avatarId: 'asset-376b651245',
  },
  {
    id: 'testimonial-feedback-vinatex',
    locale: 'vi',
    person: 'Anh Đức Anh',
    quote: {
      format: 'sanitized-html',
      html: 'Với sự ăn ý trong lần hợp tác đầu tiên về dự án website của Công ty, Tập đoàn Vinatex đánh giá cao chất lượng dịch vụ của Sova và tiếp tục hợp tác cho các dự án tiếp theo về Digital Marketing.',
      assetIds: [],
      sources: [{ file: 'index.html', line: 2392 }],
    },
    sources: [{ file: 'index.html', line: 2384 }],
    role: 'Giám đốc Trung tâm nghiên cứu sản phẩm Vinatex',
    avatarId: 'asset-7ba9399727',
  },
  {
    id: 'testimonial-feedback-ten',
    locale: 'en',
    person: 'Mr Binh',
    quote: {
      format: 'sanitized-html',
      html: 'I have consulted with many different website design companies, but it was only when I came to Sova that I decided to collaborate. You made me feel that you are different, dedicated, handle everything yourself, and truly listen.',
      assetIds: [],
      sources: [{ file: 'en/home/index.html', line: 2165 }],
    },
    sources: [{ file: 'en/home/index.html', line: 2157 }],
    role: 'TGD TEN Group',
    avatarId: 'asset-b6f667ae8f',
  },
  {
    id: 'testimonial-feedback-dong-a',
    locale: 'en',
    person: 'Ms Do My Linh',
    quote: {
      format: 'sanitized-html',
      html: 'As a long-term partner with Sova, we completely trust them to handle and implement digital product development projects that require high standards for user experience for our clients and partners.',
      assetIds: [],
      sources: [{ file: 'en/home/index.html', line: 2244 }],
    },
    sources: [{ file: 'en/home/index.html', line: 2236 }],
    role: 'Founder of Dong A Aesthetic Hospital',
    avatarId: 'asset-376b651245',
  },
  {
    id: 'testimonial-feedback-vinatex',
    locale: 'en',
    person: 'Mr Duc Anh',
    quote: {
      format: 'sanitized-html',
      html: "With the seamless collaboration on the first website project for the company, Vinatex Group highly appreciates the quality of Sova's services and continues to collaborate on subsequent Digital Marketing projects.",
      assetIds: [],
      sources: [{ file: 'en/home/index.html', line: 2323 }],
    },
    sources: [{ file: 'en/home/index.html', line: 2315 }],
    role: 'Director of Vinatex Product Research Center',
    avatarId: 'asset-7ba9399727',
  },
];
