// Dev-only importer: `npm run import`. Reads ../eras-clone (read-only) and writes src/data/{faq,
// posts,post-categories,listings,projects,project-categories,content,assets}.ts.
// Not run in CI (no source mirror there); CI guards the committed output instead.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { format, resolveConfig } from 'prettier';
import { crossCheck, importFAQs } from './faq.ts';
import type { Stats } from './html.ts';
import { importPosts } from './posts.ts';
import { importProjects } from './projects.ts';
import { createAssetRegistry } from './assets.ts';

const here = import.meta.dirname;
const ERAS_CLONE_DIR = path.resolve(
  process.env.ERAS_CLONE_DIR ?? path.join(here, '../../../../../eras-clone'),
);
const DOCS_DIR = path.resolve(process.env.DOCS_DIR ?? path.join(here, '../../../../docs'));
const DATA = path.resolve(here, '../../src/data');
const HEADER = '// Generated by scripts/import (npm run import) — do not edit.';

async function writeTs(file: string, body: string) {
  const options = await resolveConfig(file);
  const text = await format(body, { ...options, filepath: file });
  const changed = !existsSync(file) || readFileSync(file, 'utf8') !== text;
  if (changed) writeFileSync(file, text);
  console.log(`${changed ? 'wrote' : 'unchanged'} ${path.relative(process.cwd(), file)}`);
}

async function main() {
  if (!existsSync(path.join(ERAS_CLONE_DIR, 'index.html')))
    throw new Error(`Source mirror not found at ${ERAS_CLONE_DIR} (set ERAS_CLONE_DIR)`);
  const stats: Stats = { brand: 0, scrub: 0 };
  const { faqs, topics, occurrences } = importFAQs(ERAS_CLONE_DIR, stats);
  const checked = crossCheck(path.join(DOCS_DIR, 'evidence/faq-occurrences.json'), occurrences);
  console.log(
    `faq: ${checked} occurrences -> ${faqs.length} FAQs, ${topics.length} topics ` +
      `(${stats.scrub} contact scrubs, ${stats.brand} brand replacements)`,
  );
  await writeTs(
    path.join(DATA, 'faq.ts'),
    `${HEADER}
import type { FAQ, FAQTopic } from '@/types/content';

export const faqs: FAQ[] = ${JSON.stringify(faqs)};

export const faqTopics: FAQTopic[] = ${JSON.stringify(topics)};
`,
  );

  const postStats: Stats = { brand: 0, scrub: 0 };
  const assetStats: Stats = { brand: 0, scrub: 0 };
  const registry = createAssetRegistry(ERAS_CLONE_DIR, assetStats);
  const { posts, categories, snapshots } = importPosts(ERAS_CLONE_DIR, registry, postStats);
  console.log(
    `posts: ${posts.length} posts, ${categories.length} categories, ${snapshots.length} listing ` +
      `pages (${postStats.scrub} contact scrubs, ${postStats.brand} brand replacements)`,
  );
  await writeTs(
    path.join(DATA, 'posts.ts'),
    `${HEADER}
import type { Post } from '@/types/content';

export const posts: Post[] = ${JSON.stringify(posts)};
`,
  );
  await writeTs(
    path.join(DATA, 'post-categories.ts'),
    `${HEADER}
import type { PostCategory, SourceRef } from '@/types/content';

export const postCategories: (PostCategory & { sources: SourceRef[] })[] = ${JSON.stringify(categories)};
`,
  );
  await writeTs(
    path.join(DATA, 'listings.ts'),
    `${HEADER}
import type { ListingSettings, ListingSnapshot } from '@/types/content';

export const listingSettings: ListingSettings[] = [];
export const listingSnapshots: ListingSnapshot[] = ${JSON.stringify(snapshots)};
`,
  );

  const projectStats: Stats = { brand: 0, scrub: 0 };
  const project = importProjects(ERAS_CLONE_DIR, registry, projectStats);
  console.log(
    `projects: ${project.projects.length} projects, ${project.categories.length} categories, ` +
      `${project.terms.length} delivery terms ` +
      `(${projectStats.scrub} contact scrubs, ${projectStats.brand} brand replacements)`,
  );
  await writeTs(
    path.join(DATA, 'projects.ts'),
    `${HEADER}
import type { Project } from '@/types/content';

export const projects: Project[] = ${JSON.stringify(project.projects)};
`,
  );
  await writeTs(
    path.join(DATA, 'project-categories.ts'),
    `${HEADER}
import type { ProjectCategory, SourceRef } from '@/types/content';

export const projectCategories: (ProjectCategory & { sources: SourceRef[] })[] = ${JSON.stringify(project.categories)};
`,
  );
  await writeTs(
    path.join(DATA, 'content.ts'),
    `${HEADER}
import type { EntityId, RichContent } from '@/types/content';

// Utility copy and project delivery terms (Project.deliveryTermsId).
export const utilityContent: { id: EntityId; body: RichContent }[] = ${JSON.stringify(project.terms)};
`,
  );

  const assets = registry.list();
  console.log(
    `assets: ${assets.length} (${assets.filter((a) => a.status === 'local').length} local) ` +
      `(${assetStats.scrub} contact scrubs, ${assetStats.brand} brand replacements in alt text)`,
  );
  await writeTs(
    path.join(DATA, 'assets.ts'),
    `${HEADER}
import type { AssetRef } from '@/types/content';

export const assets: AssetRef[] = ${JSON.stringify(assets)};
`,
  );
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
