// Dev-only importer: `npm run import`. Reads ../eras-clone (read-only) and writes src/data/faq.ts.
// Not run in CI (no source mirror there); CI guards the committed output instead.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { format, resolveConfig } from 'prettier';
import { crossCheck, importFAQs, type Stats } from './faq.ts';

const here = import.meta.dirname;
const ERAS_CLONE_DIR = path.resolve(
  process.env.ERAS_CLONE_DIR ?? path.join(here, '../../../../../eras-clone'),
);
const DOCS_DIR = path.resolve(process.env.DOCS_DIR ?? path.join(here, '../../../../docs'));
const OUT = path.resolve(here, '../../src/data/faq.ts');

async function writeTs(file: string, body: string) {
  const options = await resolveConfig(file);
  const text = await format(body, { ...options, filepath: file });
  const changed = !existsSync(file) || readFileSync(file, 'utf8') !== text;
  if (changed) writeFileSync(file, text);
  console.log(`${changed ? 'wrote' : 'unchanged'} ${path.relative(process.cwd(), file)}`);
}

async function main() {
  if (!existsSync(path.join(ERAS_CLONE_DIR, 'index.html')))
    throw new Error(`Source mirror not found at ${ERAS_CLONE_DIR} (set ERAS_CLONE_DIR)`);
  const stats: Stats = { brand: 0, scrub: 0 };
  const { faqs, topics, occurrences } = importFAQs(ERAS_CLONE_DIR, stats);
  const checked = crossCheck(path.join(DOCS_DIR, 'evidence/faq-occurrences.json'), occurrences);
  console.log(
    `faq: ${checked} occurrences -> ${faqs.length} FAQs, ${topics.length} topics ` +
      `(${stats.scrub} contact scrubs, ${stats.brand} brand replacements)`,
  );
  await writeTs(
    OUT,
    `// Generated by scripts/import (npm run import) — do not edit.
import type { FAQ, FAQTopic } from '@/types/content';

export const faqs: FAQ[] = ${JSON.stringify(faqs)};

export const faqTopics: FAQTopic[] = ${JSON.stringify(topics)};
`,
  );
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
