// Dev-only importer: `npm run import`. Reads ../eras-clone (read-only) and writes src/data/{faq,
// posts,post-categories,listings,projects,project-categories,content,testimonials,partners,routes,
// stats,navigation,assets}.ts, services/*.ts, pricing/*.ts and pages/*.ts. site.ts is hand-written.
// Not run in CI (no source mirror there); CI guards the committed output instead.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { format, resolveConfig } from 'prettier';
import { crossCheck, importFAQs } from './faq.ts';
import { assertNoLeak, type Stats } from './html.ts';
import { importPosts } from './posts.ts';
import { importProjects } from './projects.ts';
import { createAssetRegistry } from './assets.ts';
import { importRoutes } from './routes.ts';
import { importNavigation } from './navigation.ts';
import { importPages } from './pages.ts';
import { importServices } from './services.ts';
import { importSocial } from './social.ts';
import type { Pricing, Service } from '../../src/types/content.ts';

const here = import.meta.dirname;
const ERAS_CLONE_DIR = path.resolve(
  process.env.ERAS_CLONE_DIR ?? path.join(here, '../../../../../eras-clone'),
);
const DOCS_DIR = path.resolve(process.env.DOCS_DIR ?? path.join(here, '../../../../docs'));
const DATA = path.resolve(here, '../../src/data');
const HEADER = '// Generated by scripts/import (npm run import) — do not edit.';

async function writeTs(file: string, body: string) {
  assertNoLeak(path.relative(DATA, file), body);
  const options = await resolveConfig(file);
  const text = await format(body, { ...options, filepath: file });
  const changed = !existsSync(file) || readFileSync(file, 'utf8') !== text;
  if (changed) writeFileSync(file, text);
  console.log(`${changed ? 'wrote' : 'unchanged'} ${path.relative(process.cwd(), file)}`);
}

async function main() {
  if (!existsSync(path.join(ERAS_CLONE_DIR, 'index.html')))
    throw new Error(`Source mirror not found at ${ERAS_CLONE_DIR} (set ERAS_CLONE_DIR)`);
  const stats: Stats = { brand: 0, scrub: 0 };
  const { faqs, topics, occurrences, servicePlacements } = importFAQs(ERAS_CLONE_DIR, stats);
  const checked = crossCheck(path.join(DOCS_DIR, 'evidence/faq-occurrences.json'), occurrences);
  console.log(
    `faq: ${checked} occurrences -> ${faqs.length} FAQs, ${topics.length} topics ` +
      `(${stats.scrub} contact scrubs, ${stats.brand} brand replacements)`,
  );
  await writeTs(
    path.join(DATA, 'faq.ts'),
    `${HEADER}
import type { FAQ, FAQTopic } from '@/types/content';

export const faqs: FAQ[] = ${JSON.stringify(faqs)};

export const faqTopics: FAQTopic[] = ${JSON.stringify(topics)};
`,
  );

  const postStats: Stats = { brand: 0, scrub: 0 };
  const assetStats: Stats = { brand: 0, scrub: 0 };
  const registry = createAssetRegistry(ERAS_CLONE_DIR, assetStats);
  const { posts, categories, snapshots } = importPosts(ERAS_CLONE_DIR, registry, postStats);
  console.log(
    `posts: ${posts.length} posts, ${categories.length} categories, ${snapshots.length} listing ` +
      `pages (${postStats.scrub} contact scrubs, ${postStats.brand} brand replacements)`,
  );
  await writeTs(
    path.join(DATA, 'posts.ts'),
    `${HEADER}
import type { Post } from '@/types/content';

export const posts: Post[] = ${JSON.stringify(posts)};
`,
  );
  await writeTs(
    path.join(DATA, 'post-categories.ts'),
    `${HEADER}
import type { PostCategory, SourceRef } from '@/types/content';

export const postCategories: (PostCategory & { sources: SourceRef[] })[] = ${JSON.stringify(categories)};
`,
  );

  const projectStats: Stats = { brand: 0, scrub: 0 };
  const project = importProjects(ERAS_CLONE_DIR, registry, projectStats);
  console.log(
    `projects: ${project.projects.length} projects, ${project.categories.length} categories, ` +
      `${project.terms.length} delivery terms ` +
      `(${projectStats.scrub} contact scrubs, ${projectStats.brand} brand replacements)`,
  );
  await writeTs(
    path.join(DATA, 'projects.ts'),
    `${HEADER}
import type { Project } from '@/types/content';

export const projects: Project[] = ${JSON.stringify(project.projects)};
`,
  );
  await writeTs(
    path.join(DATA, 'project-categories.ts'),
    `${HEADER}
import type { ProjectCategory, SourceRef } from '@/types/content';

export const projectCategories: (ProjectCategory & { sources: SourceRef[] })[] = ${JSON.stringify(project.categories)};
`,
  );

  const serviceStats: Stats = { brand: 0, scrub: 0 };
  const { services, pricing } = importServices(ERAS_CLONE_DIR, registry, serviceStats, {
    placements: servicePlacements,
    projectIdBySlug: new Map(project.projects.map((p) => [p.slug, p.id])),
  });
  const { testimonials, partners } = importSocial(ERAS_CLONE_DIR, registry, serviceStats);
  for (const service of services)
    for (const id of service.testimonialIds)
      if (!testimonials.some((t) => t.id === id && t.locale === service.locale))
        throw new Error(`${service.sources[0].file}: testimonial ${id} not imported`);
  console.log(
    `services: ${services.length} services, ${pricing.length} pricing, ${testimonials.length} ` +
      `testimonials, ${partners.length} partners ` +
      `(${serviceStats.scrub} contact scrubs, ${serviceStats.brand} brand replacements)`,
  );
  const byKey = <T extends { serviceKey?: string; key?: string }>(list: T[], key: string) =>
    list.filter((r) => (r.key ?? r.serviceKey) === key);
  for (const key of new Set(services.map((s) => s.key))) {
    await writeTs(
      path.join(DATA, `services/${key}.ts`),
      `${HEADER}
import type { Service } from '@/types/content';

export const ${key}Services: Service[] = ${JSON.stringify(byKey<Service>(services, key))};
`,
    );
  }
  for (const key of new Set(pricing.map((p) => p.serviceKey))) {
    await writeTs(
      path.join(DATA, `pricing/${key}.ts`),
      `${HEADER}
import type { Pricing } from '@/types/content';

export const ${key}Pricing: Pricing[] = ${JSON.stringify(byKey<Pricing>(pricing, key))};
`,
    );
  }
  await writeTs(
    path.join(DATA, 'testimonials.ts'),
    `${HEADER}
import type { Testimonial } from '@/types/content';

export const testimonials: Testimonial[] = ${JSON.stringify(testimonials)};
`,
  );
  await writeTs(
    path.join(DATA, 'partners.ts'),
    `${HEADER}
import type { Partner } from '@/types/content';

export const partners: Partner[] = ${JSON.stringify(partners)};
`,
  );

  const routes = importRoutes(DOCS_DIR, ERAS_CLONE_DIR, {
    posts,
    projects: project.projects,
    postCategories: categories,
    projectCategories: project.categories,
    services,
  });
  console.log(
    `routes: ${routes.length} routes, ${routes.reduce((n, r) => n + r.aliases.length, 0)} aliases, ` +
      `${routes.filter((r) => r.counterpartId).length} with a counterpart`,
  );
  await writeTs(
    path.join(DATA, 'routes.ts'),
    `${HEADER}
import type { RouteEntry } from '@/types/content';

export const routes: RouteEntry[] = ${JSON.stringify(routes)};
`,
  );

  const pageStats: Stats = { brand: 0, scrub: 0 };
  const page = importPages(ERAS_CLONE_DIR, registry, pageStats, {
    routes,
    projectIdBySlug: new Map(project.projects.map((p) => [p.slug, p.id])),
    postIdBySlug: new Map(posts.map((p) => [p.slug, p.id])),
    services,
    partnerIds: new Set(partners.map((p) => p.id)),
  });
  const { navigation, dropped } = importNavigation(ERAS_CLONE_DIR, routes, pageStats);
  for (const link of dropped) console.log(`nav dropped ${link}`);
  console.log(
    `pages: ${page.homePages.length} home, ${page.aboutPages.length} about, ` +
      `${page.contactPages.length} contact, ${page.legalPages.length} legal, ` +
      `${page.paymentGuides.length} payment, ${page.profiles.length} profile, ` +
      `${page.stats.length} stats, ${page.listingSettings.length} listing settings, ` +
      `${navigation.length} navigation (${dropped.length} links dropped) ` +
      `(${pageStats.scrub} contact scrubs, ${pageStats.brand} brand replacements)`,
  );
  const pageFiles: [file: string, type: string, name: string, value: unknown][] = [
    ['pages/home.ts', 'HomePageRecord', 'homePages', page.homePages],
    ['pages/about.ts', 'AboutPageRecord', 'aboutPages', page.aboutPages],
    ['pages/contact.ts', 'ContactPageContent', 'contactPages', page.contactPages],
    ['pages/profile.ts', 'CompanyProfileContent', 'profiles', page.profiles],
    ['stats.ts', 'Stat', 'stats', page.stats],
    ['navigation.ts', 'Navigation', 'navigation', navigation],
  ];
  for (const [file, type, name, value] of pageFiles)
    await writeTs(
      path.join(DATA, file),
      `${HEADER}
import type { ${type} } from '@/types/content';

export const ${name}: ${type}[] = ${JSON.stringify(value)};
`,
    );
  await writeTs(
    path.join(DATA, 'pages/legal.ts'),
    `${HEADER}
import type { LegalPage, PaymentGuideContent } from '@/types/content';

export const legalPages: LegalPage[] = ${JSON.stringify(page.legalPages)};

export const paymentGuides: PaymentGuideContent[] = ${JSON.stringify(page.paymentGuides)};
`,
  );
  await writeTs(
    path.join(DATA, 'listings.ts'),
    `${HEADER}
import type { ListingSettings, ListingSnapshot } from '@/types/content';

export const listingSettings: ListingSettings[] = ${JSON.stringify(page.listingSettings)};
export const listingSnapshots: ListingSnapshot[] = ${JSON.stringify(snapshots)};

export const blogListingCopy = {
  vi: {
    title: 'Góc nhìn',
    breadcrumbHome: 'Trang chủ',
    breadcrumbBlog: 'Góc nhìn',
    readMore: 'Đọc tiếp →',
    searchTitle: 'Tìm kiếm',
    categoriesTitle: 'Danh mục bài viết',
    searchPlaceholder: 'Search…',
    searchSubmit: 'Gửi',
    pagination: {
      nav: 'Phân trang bài viết',
      prev: 'Trang trước',
      next: 'Trang tiếp theo',
    },
  },
  en: {
    title: 'Insight',
    breadcrumbHome: 'Home',
    breadcrumbBlog: 'Insight',
    readMore: 'Read more →',
    searchTitle: 'Search',
    categoriesTitle: 'Categories',
    searchPlaceholder: 'Search…',
    searchSubmit: 'Submit',
    pagination: {
      nav: 'Post pagination',
      prev: 'Previous page',
      next: 'Next page',
    },
  },
};

export const blogDetailCopy = {
  breadcrumbHome: 'Trang chủ',
  breadcrumbBlog: 'Góc nhìn',
  breadcrumbCurrent: 'Chi tiết',
  headingBackgroundImage: '/wp-content/uploads/2024/03/ec9c55cfcb4d0c64ecafd52d957c13e9.png',
};

export const projectListingCopy = {
  vi: {
    filterAll: 'Tất cả',
    emptyMessage: 'Không có dự án nào.',
    loadingMessage: 'Đang tải...',
    pagination: {
      nav: 'Phân trang dự án',
      prev: 'Trang trước',
      next: 'Trang tiếp theo',
    },
  },
  en: {
    filterAll: 'All',
    emptyMessage: 'No projects found.',
    loadingMessage: 'Đang tải...',
    pagination: {
      nav: 'Project pagination',
      prev: 'Previous page',
      next: 'Next page',
    },
  },
};
`,
  );
  await writeTs(
    path.join(DATA, 'content.ts'),
    `${HEADER}
import type { UtilityContent } from '@/types/content';

// Utility copy and project delivery terms (Project.deliveryTermsId).
export const utilityContent: UtilityContent[] = ${JSON.stringify([...project.terms, ...page.thankYou])};
`,
  );

  const assets = [...registry.list(), page.wordmark];
  console.log(
    `assets: ${assets.length} (${assets.filter((a) => a.status === 'local').length} local) ` +
      `(${assetStats.scrub} contact scrubs, ${assetStats.brand} brand replacements in alt text)`,
  );
  await writeTs(
    path.join(DATA, 'assets.ts'),
    `${HEADER}
import type { AssetRef } from '@/types/content';

export const assets: AssetRef[] = ${JSON.stringify(assets)};
`,
  );
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
