// Generated by scripts/import (npm run import) — do not edit.
import type { FAQPageContent } from '@/types/content';

export const faqPages: FAQPageContent[] = [
  {
    id: 'faq-vi',
    locale: 'vi',
    path: '/cau-hoi-thuong-gap/',
    title: 'CÂU HỎI THƯỜNG GẶP',
    sources: [{ file: 'cau-hoi-thuong-gap/index.html', line: 618, sourceId: '7209' }],
    translationKey: 'faq',
    breadcrumb: { homeLabel: 'Trang chủ', current: 'Câu hỏi thường gặp' },
    seo: {
      title: 'Câu hỏi thường gặp - Công ty thiết kế website chuyên nghiệp | Sova',
      description: 'Trang chủ Câu hỏi thường gặp',
      canonicalPath: '/cau-hoi-thuong-gap/',
    },
  },
  {
    id: 'faq-en',
    locale: 'en',
    path: '/en/faq/',
    title: 'FAQ',
    sources: [{ file: 'en/faq/index.html', line: 618, sourceId: '7328' }],
    translationKey: 'faq',
    breadcrumb: { homeLabel: 'Home', current: 'FAQ' },
    seo: {
      title: 'FAQ - Công ty thiết kế website chuyên nghiệp | Sova',
      description: 'Home FAQ',
      canonicalPath: '/en/faq/',
    },
  },
];
