// Generated by scripts/import (npm run import) — do not edit.
import type { CompanyProfileContent } from '@/types/content';

export const profiles: CompanyProfileContent[] = [
  {
    id: 'profile-en',
    locale: 'en',
    path: '/en/porfolio-eras-vietnam/',
    title: 'Portfolio Sova',
    sources: [{ file: 'en/porfolio-eras-vietnam/index.html', line: 625, sourceId: '7355' }],
    translationKey: 'profile',
    coverId: 'asset-3a2f0e6140',
    pdfAssetId: 'asset-eeb72bb0f1',
    seo: {
      title: 'Porfolio Sova - Công ty thiết kế website chuyên nghiệp | Sova',
      description: 'Trang chủ / Porfolio Sova',
      canonicalPath: '/en/porfolio-eras-vietnam/',
      imageId: 'asset-7bf27997e2',
    },
  },
  {
    id: 'profile-vi',
    locale: 'vi',
    path: '/ho-so-nang-luc-eras-vietnam/',
    title: 'Hồ Sơ Năng Lực Sova',
    sources: [{ file: 'ho-so-nang-luc-eras-vietnam/index.html', line: 625, sourceId: '7211' }],
    translationKey: 'profile',
    coverId: 'asset-3a2f0e6140',
    pdfAssetId: 'asset-e6d8764e5f',
    seo: {
      title: 'Hồ sơ năng lực Sova - Công ty thiết kế website chuyên nghiệp | Sova',
      description: 'Trang chủ / Porfolio Sova',
      canonicalPath: '/ho-so-nang-luc-eras-vietnam/',
      imageId: 'asset-7bf27997e2',
    },
  },
];
