// Generated by scripts/import (npm run import) — do not edit.
import type { Service } from '@/types/content';

export const brandingServices: Service[] = [
  {
    id: 'service-branding-vi',
    locale: 'vi',
    path: '/ui-ux-branding-design/',
    title: 'UI/UX, Branding Design',
    translationKey: 'service-branding',
    sources: [{ file: 'ui-ux-branding-design/index.html', line: 676, sourceId: '7238' }],
    key: 'branding',
    summary:
      'Tại Sova, chúng tôi giúp doanh nghiệp hiện thực hóa mục tiêu bằng các dịch vụ thiết kế UI/UX chuyên biệt. Quá trình này được xây dựng trên nền tảng nghiên cứu sâu về thị trường và hành vi người dùng, đảm bảo sự phù hợp với yếu tố văn hóa.',
    hero: {
      headingLines: ['UI/UX,', 'Branding Design'],
      description: {
        format: 'sanitized-html',
        html: '<p>Tại Sova, chúng tôi giúp doanh nghiệp hiện thực hóa mục tiêu bằng các dịch vụ thiết kế UI/UX chuyên biệt. Quá trình này được xây dựng trên nền tảng nghiên cứu sâu về thị trường và hành vi người dùng, đảm bảo sự phù hợp với yếu tố văn hóa.</p>',
        assetIds: [],
        sources: [{ file: 'ui-ux-branding-design/index.html', line: 702 }],
      },
      imageId: 'asset-a6e7f1bdf3',
      videoId: 'asset-ae461bc091',
      cta: { label: 'Kết nối ngay →', href: '/lien-he/' },
    },
    benefits: [
      {
        id: 'service-branding-vi-benefit-nghien-cuu-van-hoa-doanh-nghiep',
        title: 'Nghiên cứu văn hoá doanh nghiệp',
        body: {
          format: 'sanitized-html',
          html: '<p>Chúng tôi cung cấp những insights dựa trên dữ liệu linh động, nghiên cứu về đặc thù của ngành, đại diện tiếng nói của người dùng và phù hợp với mục tiêu doanh nghiệp muốn truyền tải.</p>',
          assetIds: [],
          sources: [{ file: 'ui-ux-branding-design/index.html', line: 1018 }],
        },
        iconId: 'asset-4fd98a88eb',
      },
      {
        id: 'service-branding-vi-benefit-thiet-ke-trai-nghiem-doanh-nghiep',
        title: 'Thiết kế trải nghiệm doanh nghiệp',
        body: {
          format: 'sanitized-html',
          html: '<p>Đội ngũ nhà thiết kế UI/UX của chúng tôi luôn nỗ lực tạo ra các thiết kế trực quan, mang tính phát triển và chiến thắng trái tim của người dùng. Đưa khách hàng tới sát gần hơn với doanh nghiệp.</p>',
          assetIds: [],
          sources: [{ file: 'ui-ux-branding-design/index.html', line: 1084 }],
        },
        iconId: 'asset-10b3066e33',
      },
      {
        id: 'service-branding-vi-benefit-phat-trien-chien-luoc-san-pham',
        title: 'Phát triển chiến lược sản phẩm',
        body: {
          format: 'sanitized-html',
          html: '<p>Chúng tôi giúp doanh nghiệp biến thiết kế đơn thuần thành sản phẩm kỹ thuật số với khả năng thích ứng tốt và mang tính phát triển, thân thiện với người sử dụng hơn.</p>',
          assetIds: [],
          sources: [{ file: 'ui-ux-branding-design/index.html', line: 1150 }],
        },
        iconId: 'asset-c1702f3eb0',
      },
      {
        id: 'service-branding-vi-benefit-tao-dung-gia-tri-ben-vung',
        title: 'Tạo dựng giá trị bền vững',
        body: {
          format: 'sanitized-html',
          html: '<p>Sova đặt mục tiêu mang lại giá trị bền vững cho khách hàng bằng liên tục hoàn thiện, tăng cường thương hiệu và tăng doanh số bán hàng. Đồng thời, Sova tuân thủ các quy định và tiêu chuẩn đạo đức trong lĩnh vực, đảm bảo rằng khách hàng nhận được một dịch vụ chất lượng tốt nhất.</p>',
          assetIds: [],
          sources: [{ file: 'ui-ux-branding-design/index.html', line: 1216 }],
        },
        iconId: 'asset-715577a59b',
      },
    ],
    faqs: [
      { faqId: 'faq-vi-2007864068', order: 1 },
      { faqId: 'faq-vi-1956117972', order: 2 },
      { faqId: 'faq-vi-3192151536', order: 3 },
      { faqId: 'faq-vi-3629795028', order: 4 },
      { faqId: 'faq-vi-3863365247', order: 5 },
      { faqId: 'faq-vi-2387206707', order: 6 },
      { faqId: 'faq-vi-1746329293', order: 7 },
      { faqId: 'faq-vi-4075613316', order: 8 },
      { faqId: 'faq-vi-1004523356', order: 9 },
      { faqId: 'faq-vi-3140419566', order: 10 },
    ],
    testimonialIds: [
      'testimonial-feedback-ten',
      'testimonial-feedback-dong-a',
      'testimonial-feedback-vinatex',
    ],
    featuredProjectIds: [
      'project-2348',
      'project-2182',
      'project-2176',
      'project-2170',
      'project-2161',
      'project-2120',
    ],
    seo: {
      title: 'UI/UX, Branding Design - Công ty thiết kế website chuyên nghiệp | Sova',
      description: 'Trang chủ / Dịch vụ / UI/UX, Branding Design',
      canonicalPath: '/ui-ux-branding-design/',
      imageId: 'asset-16c8c6ed5f',
    },
    offerings: [
      {
        id: 'service-branding-vi-offering-thiet-ke-logo-thuong-hieu',
        title: 'THIẾT KẾ LOGO THƯƠNG HIỆU',
        content: {
          format: 'sanitized-html',
          html: '<p>Logo không chỉ là hình ảnh đại diện cho thương hiệu mà còn là công cụ giúp tạo dấu ấn mạnh mẽ trong tâm trí khách hàng.</p><ul><li>Thiết kế độc quyền</li><li>Không trùng lặp</li><li>Phong cách thiết kế đa dạng</li><li>Định hướng thiết kế rõ ràng</li><li>Bộ nhận diện đầy đủ</li><li>Chỉnh sửa theo yêu cầu</li><li>Hoàn thành nhanh chóng</li></ul><p><a href="{{site.zaloHref}}">Tư vấn miễn phí   → </a></p>',
          assetIds: [],
          sources: [{ file: 'ui-ux-branding-design/index.html', line: 1350 }],
        },
      },
      {
        id: 'service-branding-vi-offering-thiet-ke-ui-ux-web-app',
        title: 'THIẾT KẾ UI/UX WEB/APP',
        content: {
          format: 'sanitized-html',
          html: '<p>Dịch vụ thiết kế UI/UX chuyên nghiệp giúp nâng cao sự tương tác, tăng tỷ lệ chuyển đổi &amp; tạo dấu ấn thương hiệu mạnh mẽ.</p><ul><li>Giao diện hiện đại &amp; Ấn tượng</li><li>Tối ưu trải nghiệm người dùng</li><li>Thiết Kế Responsive đa thiết bị</li><li>Prototype &amp; Demo trực quan</li><li>Bàn giao đầy đủ file thiết kế</li><li>Điều chỉnh theo yêu cầu</li><li>Hoàn thành nhanh chóng</li></ul><p><a href="{{site.zaloHref}}">Tư vấn miễn phí   → </a></p>',
          assetIds: [],
          sources: [{ file: 'ui-ux-branding-design/index.html', line: 1587 }],
        },
      },
      {
        id: 'service-branding-vi-offering-thiet-ke-nhan-dien-thuong-hieu',
        title: 'THIẾT KẾ NHẬN DIỆN THƯƠNG HIỆU',
        content: {
          format: 'sanitized-html',
          html: '<p>Một bộ nhận diện thương hiệu chuyên nghiệp, đồng nhất giúp tăng độ nhận diện, tạo dấu ấn mạnh mẽ &amp; nâng cao uy tín trong mắt khách hàng.</p><ul><li>Tư vấn miễn phí</li><li>Dễ dàng nhận diện</li><li>Bộ nhận diện hoàn chỉnh</li><li>Sáng tạo &amp; Khác biệt</li><li>Bàn giao file gốc &amp; HDSD</li><li>Hỗ trợ điều chỉnh</li><li>Hoàn thành nhanh chóng</li></ul><p><a href="{{site.zaloHref}}">Tư vấn miễn phí   → </a></p>',
          assetIds: [],
          sources: [{ file: 'ui-ux-branding-design/index.html', line: 1815 }],
        },
      },
      {
        id: 'service-branding-vi-offering-thiet-ke-nhan-dien-tai-diem-ban',
        title: 'THIẾT KẾ NHẬN DIỆN TẠI ĐIỂM BÁN',
        content: {
          format: 'sanitized-html',
          html: '<p>Một hệ thống nhận diện tại điểm bán chuyên nghiệp, thu hút &amp; đồng nhất giúp thương hiệu nổi bật, tạo ấn tượng mạnh mẽ với khách hàng và thúc đẩy doanh số bán hàng.</p><ul><li>Biển hiệu &amp; Trang trí không gian</li><li>POSM – Hỗ trợ bán hàng</li><li>Bao bì &amp; Ấn phẩm đồng bộ</li><li>Đồng phục &amp; Phụ kiện nhận diện</li><li>Hoàn thành nhanh chóng</li></ul><p><a href="{{site.zaloHref}}">Tư vấn miễn phí   → </a></p>',
          assetIds: [],
          sources: [{ file: 'ui-ux-branding-design/index.html', line: 2042 }],
        },
      },
    ],
    sectionCopy: {
      benefits: {
        eyebrow: 'Dịch vụ thiết kế UI/UX',
        title: 'Tại Sova',
        description: 'Chúng tôi thiết kế dựa trên cốt lõi văn hóa doanh nghiệp',
      },
      offerings: { eyebrow: 'Những dịch vụ', title: 'Thiết kế UI/UX' },
      projects: {
        eyebrow: 'Sova',
        title: 'Dự án chứa đựng Tâm huyết Sáng tạo',
        titleLines: ['Dự án chứa đựng', 'Tâm huyết Sáng tạo'],
      },
      testimonials: {
        eyebrow: 'Sova',
        title: 'Khách hàng nhận xét về chúng tôi',
        titleLines: ['Khách hàng nhận xét', 'về chúng tôi'],
      },
      faq: { title: 'Những câu hỏi thường gặp' },
    },
  },
  {
    id: 'service-branding-en',
    locale: 'en',
    path: '/en/ui-ux-branding-design-2/',
    title: 'UI/UX, Branding Design',
    translationKey: 'service-branding',
    sources: [{ file: 'en/ui-ux-branding-design-2/index.html', line: 676, sourceId: '7381' }],
    key: 'branding',
    summary:
      'Sova empower businesses to achieve their goals through specialized UI/UX design services. Our process is grounded in deep research into market dynamics and user behavior, ensuring that every design aligns with both functional needs and cultural context.',
    hero: {
      headingLines: ['UI/UX,', 'Branding Design'],
      description: {
        format: 'sanitized-html',
        html: '<p>Sova empower businesses to achieve their goals through specialized UI/UX design services. Our process is grounded in deep research into market dynamics and user behavior, ensuring that every design aligns with both functional needs and cultural context.</p>',
        assetIds: [],
        sources: [{ file: 'en/ui-ux-branding-design-2/index.html', line: 702 }],
      },
      imageId: 'asset-a6e7f1bdf3',
      videoId: 'asset-ae461bc091',
      cta: { label: 'Connect now →', href: '/en/contact-us/' },
    },
    benefits: [
      {
        id: 'service-branding-en-benefit-corporate-culture-research',
        title: 'Corporate Culture Research',
        body: {
          format: 'sanitized-html',
          html: '<p>We provide actionable insights backed by dynamic data, tailored to your industry characteristics. Our approach captures the voice of the user while aligning with your business goals and brand narrative.</p>',
          assetIds: [],
          sources: [{ file: 'en/ui-ux-branding-design-2/index.html', line: 1018 }],
        },
        iconId: 'asset-4fd98a88eb',
      },
      {
        id: 'service-branding-en-benefit-enterprise-experience-design',
        title: 'Enterprise Experience Design',
        body: {
          format: 'sanitized-html',
          html: '<p>Our UI/UX design team is committed to crafting intuitive, growth-oriented interfaces that resonate with users. We bridge the gap between customers and your business through emotionally intelligent and user-centered design.</p>',
          assetIds: [],
          sources: [{ file: 'en/ui-ux-branding-design-2/index.html', line: 1084 }],
        },
        iconId: 'asset-10b3066e33',
      },
      {
        id: 'service-branding-en-benefit-product-strategy-development',
        title: 'Product Strategy Development',
        body: {
          format: 'sanitized-html',
          html: '<p>We transform design ideas into scalable digital products with high adaptability and user-friendliness. Our goal is to ensure every product not only works — but works for your users.</p>',
          assetIds: [],
          sources: [{ file: 'en/ui-ux-branding-design-2/index.html', line: 1150 }],
        },
        iconId: 'asset-c1702f3eb0',
      },
      {
        id: 'service-branding-en-benefit-building-sustainable-value',
        title: 'Building Sustainable Value',
        body: {
          format: 'sanitized-html',
          html: '<p>Sova aim to deliver long-term value by enhancing your brand presence, improving user engagement, and driving business growth. We adhere to industry standards and ethical practices to guarantee the highest quality service for every client.</p>',
          assetIds: [],
          sources: [{ file: 'en/ui-ux-branding-design-2/index.html', line: 1216 }],
        },
        iconId: 'asset-715577a59b',
      },
    ],
    faqs: [
      { faqId: 'faq-en-300660932', order: 1 },
      { faqId: 'faq-en-1377652266', order: 2 },
      { faqId: 'faq-en-4147201443', order: 3 },
      { faqId: 'faq-en-3423016952', order: 4 },
      { faqId: 'faq-en-1570092550', order: 5 },
      { faqId: 'faq-en-752577294', order: 6 },
      { faqId: 'faq-en-2021483240', order: 7 },
      { faqId: 'faq-en-1048619801', order: 8 },
      { faqId: 'faq-en-100463461', order: 9 },
      { faqId: 'faq-en-918449609', order: 10 },
    ],
    testimonialIds: [
      'testimonial-feedback-ten',
      'testimonial-feedback-dong-a',
      'testimonial-feedback-vinatex',
    ],
    featuredProjectIds: [],
    seo: {
      title: 'UI/UX, Branding Design - Công ty thiết kế website chuyên nghiệp | Sova',
      description: 'Home / Services / UI/UX, Branding Design',
      canonicalPath: '/en/ui-ux-branding-design-2/',
      imageId: 'asset-16c8c6ed5f',
    },
    offerings: [
      {
        id: 'service-branding-en-offering-brand-logo-design',
        title: 'BRAND LOGO DESIGN',
        content: {
          format: 'sanitized-html',
          html: '<p>A logo is more than just a visual symbol — it’s a powerful tool to establish a lasting impression in the minds of your customers.</p><ul><li>Exclusive Design</li><li>No Duplicates</li><li>Diverse Design Styles</li><li>Clear Design Direction</li><li>Complete Brand Identity Package</li><li>Revision on Request</li><li>Fast Turnaround</li></ul><p><a href="{{site.zaloHref}}">Free Consultation   → </a></p>',
          assetIds: [],
          sources: [{ file: 'en/ui-ux-branding-design-2/index.html', line: 1349 }],
        },
      },
      {
        id: 'service-branding-en-offering-ui-ux-design-for-web-app',
        title: 'UI/UX DESIGN FOR WEB & APP',
        content: {
          format: 'sanitized-html',
          html: '<p>Professional UI/UX design services to enhance user engagement, boost conversion rates, and build a strong brand impression.</p><ul><li>Modern &amp; Striking Interfaces</li><li><strong>Optimized User Experience</strong></li><li>Responsive Design Across All Devices</li><li>Interactive Prototypes &amp; Visual Demos</li><li><strong>Complete Design File Handover</strong></li><li><strong>Custom Revisions Upon Request</strong></li><li>Fast Turnaround</li></ul><p><a href="{{site.zaloHref}}">Free Consultation   → </a></p>',
          assetIds: [],
          sources: [{ file: 'en/ui-ux-branding-design-2/index.html', line: 1586 }],
        },
      },
      {
        id: 'service-branding-en-offering-brand-identity-design',
        title: 'BRAND IDENTITY DESIGN',
        content: {
          format: 'sanitized-html',
          html: '<p>A professional and consistent brand identity helps enhance recognition, build trust, and create a lasting impression with your audience.</p><ul><li>Free Consultation</li><li>Easy-to-Recognize Visuals</li><li>Complete Identity Package</li><li>Creative &amp; Distinctive</li><li>Source Files &amp; User Guide Included</li><li>Flexible Revisions &amp; Support</li><li>Fast Turnaround</li></ul><p><a href="{{site.zaloHref}}">Free Consultation   → </a></p>',
          assetIds: [],
          sources: [{ file: 'en/ui-ux-branding-design-2/index.html', line: 1814 }],
        },
      },
      {
        id: 'service-branding-en-offering-retail-brand-identity-design',
        title: 'RETAIL BRAND IDENTITY DESIGN',
        content: {
          format: 'sanitized-html',
          html: '<p>A professional, cohesive, and visually compelling point-of-sale (POS) identity system enhances brand recognition, captivates customers, and drives sales performance.</p><ul><li><strong>Signage &amp; In-Store Visual Merchandising</strong></li><li>POSM (Point-of-Sale Materials)</li><li>Branded Packaging &amp; Collateral</li><li><strong>Uniforms &amp; Branded Accessories</strong></li><li>Fast Turnaround</li></ul><p><a href="{{site.zaloHref}}">Free Consultation   → </a></p>',
          assetIds: [],
          sources: [{ file: 'en/ui-ux-branding-design-2/index.html', line: 2041 }],
        },
      },
    ],
    sectionCopy: {
      benefits: {
        eyebrow: 'UI/UX Design Service',
        title: 'At Sova',
        description: 'We design with your corporate culture at the core',
      },
      offerings: { eyebrow: 'Services', title: 'UI/UX Design at Sova' },
      projects: {
        eyebrow: 'Sova',
        title: 'Some Recent Works We’re Really Proud Of.',
        titleLines: ['Some Recent Works', 'We’re Really Proud Of.'],
      },
      testimonials: { eyebrow: 'Sova', title: 'Customer Reviews' },
      faq: { title: 'Frequently Asked Questions' },
    },
  },
];
