// Generated by scripts/import (npm run import) — do not edit.
import type { Service } from '@/types/content';

export const mobileServices: Service[] = [
  {
    id: 'service-mobile-vi',
    locale: 'vi',
    path: '/thiet-ke-app-mobile/',
    title: 'Thiết kế App Mobile',
    translationKey: 'service-mobile',
    sources: [{ file: 'thiet-ke-app-mobile/index.html', line: 662, sourceId: '7229' }],
    key: 'mobile',
    summary:
      'Thiết kế phần mềm web-app mobile là giải pháp giúp doanh nghiệp quản lý công việc kinh doanh một cách có hệ thống và logic, từ đó nâng cao hiệu quả, gia tăng lợi nhuận và thúc đẩy sự phát triển.',
    homeSummary:
      'Thiết kế phần mềm web-app mobile là giải pháp giúp doanh nghiệp quản lý công việc kinh doanh có tính quy củ và logic, hiệu quả hơn, từ đó gia tăng lợi nhuận, phát triển',
    subServices: [],
    arrowHref: '/thiet-ke-app-mobile/',
    hero: {
      headingLines: ['Thiết kế App mobile', 'Chuyên Nghiệp'],
      description: {
        format: 'sanitized-html',
        html: '<p>Thiết kế phần mềm web-app mobile là giải pháp giúp doanh nghiệp quản lý công việc kinh doanh một cách có hệ thống và logic, từ đó nâng cao hiệu quả, gia tăng lợi nhuận và thúc đẩy sự phát triển.</p>',
        assetIds: [],
        sources: [{ file: 'thiet-ke-app-mobile/index.html', line: 688 }],
      },
      imageId: 'asset-d3cafa10e9',
      videoId: 'asset-ddbede9293',
      cta: { label: 'Kết nối ngay →', href: '/lien-he/' },
    },
    benefits: [
      {
        id: 'service-mobile-vi-benefit-xay-dung-thuong-hieu',
        title: 'Xây dựng thương hiệu',
        body: {
          format: 'sanitized-html',
          html: '<p>Thiết kế app mobile giúp thể hiện sự chuyên nghiệp, đầu tư bài bản về thương hiệu của mình. Gia tăng uy tín trong mắt khách hàng.</p>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-app-mobile/index.html', line: 923 }],
        },
        iconId: 'asset-2ef2e6b62f',
      },
      {
        id: 'service-mobile-vi-benefit-phat-trien-tinh-nang',
        title: 'Phát triển tính năng',
        body: {
          format: 'sanitized-html',
          html: '<p>Chúng ta có thể phát triển nhiều tính năng cho hệ thống và tích hợp vào Appmobile, áp dụng cho nhiều lĩnh vực khác nhau, từ đó nâng cao sức cạnh tranh so với các đối thủ.</p>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-app-mobile/index.html', line: 995 }],
        },
        iconId: 'asset-6a54e348d7',
      },
      {
        id: 'service-mobile-vi-benefit-gia-tang-chuyen-doi',
        title: 'Gia tăng chuyển đổi',
        body: {
          format: 'sanitized-html',
          html: '<p>Hình ảnh sản phẩm và dịch vụ được trình bày trực quan trên mobile app, giúp nâng cao trải nghiệm người dùng trên smartphone và thúc đẩy sự phát triển doanh số.</p>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-app-mobile/index.html', line: 1067 }],
        },
        iconId: 'asset-58750349df',
      },
      {
        id: 'service-mobile-vi-benefit-quan-ly-do-luong',
        title: 'Quản lý đo lường',
        body: {
          format: 'sanitized-html',
          html: '<p>Việc xây dựng Appmobile giúp doanh nghiệp quản lý và vận hành chiến lược kinh doanh hiệu quả hơn, nâng cao khả năng quản lý doanh nghiệp một cách chuyên nghiệp.</p>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-app-mobile/index.html', line: 1139 }],
        },
        iconId: 'asset-415b331b93',
      },
    ],
    faqs: [
      { faqId: 'faq-vi-1805637754', order: 1 },
      { faqId: 'faq-vi-1266606417', order: 2 },
      { faqId: 'faq-vi-1575217918', order: 3 },
      { faqId: 'faq-vi-1188570415', order: 4 },
      { faqId: 'faq-vi-3596286348', order: 5 },
      { faqId: 'faq-vi-221519185', order: 6 },
      { faqId: 'faq-vi-3235411383', order: 7 },
      { faqId: 'faq-vi-3802291076', order: 8 },
    ],
    testimonialIds: [
      'testimonial-feedback-ten',
      'testimonial-feedback-dong-a',
      'testimonial-feedback-vinatex',
    ],
    featuredProjectIds: [
      'project-2348',
      'project-2182',
      'project-2176',
      'project-2170',
      'project-2161',
      'project-2120',
    ],
    seo: {
      title: 'Thiết kế App Mobile - Công ty thiết kế website chuyên nghiệp | Sova',
      description: 'Trang chủ / Dịch vụ / Thiết kế App Mobile',
      canonicalPath: '/thiet-ke-app-mobile/',
      imageId: 'asset-f9d856fcbb',
    },
    offerings: [
      {
        id: 'service-mobile-vi-offering-loi-ich',
        title: 'LỢI ÍCH',
        content: {
          format: 'sanitized-html',
          html: '<ul><li>Tăng tính tiện lợi, cạnh tranh</li><li>Cải thiện khả năng tương tác</li><li>Xây dựng thương hiệu mạnh mẽ</li><li>Tăng cường trải nghiệm người dùng</li><li>Tăng khả năng tiếp cận khách hàng</li><li>Thu thập dữ liệu và phân tích hành vi người dùng</li><li>Khả năng kết nối và đồng bộ hóa dễ dàng</li></ul>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-app-mobile/index.html', line: 1286 }],
        },
      },
      {
        id: 'service-mobile-vi-offering-cam-ket',
        title: 'CAM KẾT',
        content: {
          format: 'sanitized-html',
          html: '<ul><li>Hỗ trợ và bảo trì liên tục</li><li>Bảo mật và bảo vệ dữ liệu</li><li>Tối ưu hóa hiệu suất và tốc độ</li><li>Thiết kế chuyên nghiệp và sáng tạo</li><li>Tính năng phù hợp với nhu cầu thực tế</li><li>Ứng dụng hoạt động mượt mà trên mọi nền tảng</li><li>Tối ưu hóa trải nghiệm người dùng (UX/UI)</li></ul>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-app-mobile/index.html', line: 1535 }],
        },
      },
      {
        id: 'service-mobile-vi-offering-san-pham-nhan-duoc',
        title: 'SẢN PHẨM NHẬN ĐƯỢC',
        content: {
          format: 'sanitized-html',
          html: '<ul><li>Hỗ trợ kỹ thuật liên tục 24/7</li><li>Mã nguồn đầy đủ (source code)</li><li>Sản phẩm thân thiện chuyên nghiệp</li><li>Đăng tải lên App Store / Google Play</li><li>Tài liệu hướng dẫn sử dụng &amp; bảo trì</li><li>File thiết kế giao diện (UI/UX Design)</li><li>Tài khoản quản lý app (nếu có upload lên App Store / CH Play)</li></ul>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-app-mobile/index.html', line: 1784 }],
        },
      },
    ],
    sectionCopy: {
      benefits: {
        eyebrow: 'Thiết kế Mobile app tại Sova',
        title: 'Phát triển lợi thế doanh nghiệp của bạn trên nền tảng di động',
      },
      offerings: {
        eyebrow: 'Why choose us?',
        title: 'Tại sao nên chọn Sova',
        titleLines: ['Tại sao nên chọn', 'Sova'],
      },
      projects: {
        eyebrow: 'Sova',
        title: 'Dự án chứa đựng Tâm huyết Sáng tạo',
        titleLines: ['Dự án chứa đựng', 'Tâm huyết Sáng tạo'],
      },
      testimonials: {
        eyebrow: 'Sova',
        title: 'Khách hàng nhận xét về chúng tôi',
        titleLines: ['Khách hàng nhận xét', 'về chúng tôi'],
      },
      faq: { title: 'Những câu hỏi thường gặp' },
    },
  },
  {
    id: 'service-mobile-en',
    locale: 'en',
    path: '/en/app-mobile-development/',
    title: 'App Mobile Development',
    translationKey: 'service-mobile',
    sources: [{ file: 'en/app-mobile-development/index.html', line: 662, sourceId: '7369' }],
    key: 'mobile',
    summary:
      'Designing web and mobile app software is a solution that helps businesses manage operations in a systematic and logical way, thereby enhancing efficiency, increasing profitability, and driving growth.',
    homeSummary:
      'Our mobile solutions (native & cross-platform) are engineered with modular architecture, robust APIs, and adaptive UI, allowing seamless performance across devices. We apply Agile methodology to continuously iterate and improve based on user feedback and business goals.',
    subServices: [],
    arrowHref: '/en/website-development/',
    hero: {
      headingLines: ['Professional', 'Mobile App Design'],
      description: {
        format: 'sanitized-html',
        html: '<p>Designing web and mobile app software is a solution that helps businesses manage operations in a systematic and logical way, thereby enhancing efficiency, increasing profitability, and driving growth.</p>',
        assetIds: [],
        sources: [{ file: 'en/app-mobile-development/index.html', line: 688 }],
      },
      imageId: 'asset-d3cafa10e9',
      videoId: 'asset-ddbede9293',
      cta: { label: 'Connect Now →', href: '/en/contact-us/' },
    },
    benefits: [
      {
        id: 'service-mobile-en-benefit-brand-building',
        title: 'Brand Building',
        body: {
          format: 'sanitized-html',
          html: '<p>Mobile app design reflects professionalism and a well-invested brand image, boosting credibility and trust in the eyes of your customers.</p>',
          assetIds: [],
          sources: [{ file: 'en/app-mobile-development/index.html', line: 923 }],
        },
        iconId: 'asset-2ef2e6b62f',
      },
      {
        id: 'service-mobile-en-benefit-feature-development',
        title: 'Feature Development',
        body: {
          format: 'sanitized-html',
          html: '<p>We can develop a wide range of features for the system and integrate them into the mobile app, applicable to various industries, thereby enhancing competitiveness compared to competitors.</p>',
          assetIds: [],
          sources: [{ file: 'en/app-mobile-development/index.html', line: 995 }],
        },
        iconId: 'asset-6a54e348d7',
      },
      {
        id: 'service-mobile-en-benefit-increasing-conversions',
        title: 'Increasing Conversions',
        body: {
          format: 'sanitized-html',
          html: '<p>Product and service images are displayed intuitively on the mobile app, improving the user experience on smartphones and driving business growth.</p>',
          assetIds: [],
          sources: [{ file: 'en/app-mobile-development/index.html', line: 1067 }],
        },
        iconId: 'asset-58750349df',
      },
      {
        id: 'service-mobile-en-benefit-manage-measurement',
        title: 'Manage Measurement',
        body: {
          format: 'sanitized-html',
          html: '<p>Building a mobile app enables businesses to manage and operate their business strategies more efficiently, enhancing the ability to manage the company in a professional manner.</p>',
          assetIds: [],
          sources: [{ file: 'en/app-mobile-development/index.html', line: 1139 }],
        },
        iconId: 'asset-415b331b93',
      },
    ],
    faqs: [
      { faqId: 'faq-en-3869735094', order: 1 },
      { faqId: 'faq-en-3119906008', order: 2 },
      { faqId: 'faq-en-3119906008', order: 3 },
      { faqId: 'faq-en-1583132685', order: 4 },
      { faqId: 'faq-en-951319751', order: 5 },
      { faqId: 'faq-en-3978360888', order: 6 },
      { faqId: 'faq-en-3714004587', order: 7 },
      { faqId: 'faq-en-815499635', order: 8 },
      { faqId: 'faq-en-1254110679', order: 9 },
    ],
    testimonialIds: [
      'testimonial-feedback-ten',
      'testimonial-feedback-dong-a',
      'testimonial-feedback-vinatex',
    ],
    featuredProjectIds: [],
    seo: {
      title: 'App Mobile Development - Công ty thiết kế website chuyên nghiệp | Sova',
      description: 'Home / Services / App Mobile Development',
      canonicalPath: '/en/app-mobile-development/',
      imageId: 'asset-f9d856fcbb',
    },
    offerings: [
      {
        id: 'service-mobile-en-offering-benefits',
        title: 'BENEFITS',
        content: {
          format: 'sanitized-html',
          html: '<ul><li>Increased Convenience &amp; Competitiveness</li><li>Improved Interactivity</li><li>Building a Strong Brand</li><li>Enhanced User Experience</li><li>Increased Customer Reach</li><li>Data Collect &amp; User Behavior Analysis</li><li>Easy Connectivity &amp; Synchronization</li></ul>',
          assetIds: [],
          sources: [{ file: 'en/app-mobile-development/index.html', line: 1285 }],
        },
      },
      {
        id: 'service-mobile-en-offering-commitments',
        title: 'COMMITMENTS',
        content: {
          format: 'sanitized-html',
          html: '<ul><li>Continuous Support &amp; Maintenance</li><li>Data Security &amp; Protection</li><li>Optimized Performance &amp; Speed</li><li>Professional &amp; Creative Design</li><li>Features Tailored to Real-World Needs</li><li>Smooth Operation Across All Platforms</li><li>Optimized User Experience (UX/UI)</li></ul>',
          assetIds: [],
          sources: [{ file: 'en/app-mobile-development/index.html', line: 1534 }],
        },
      },
      {
        id: 'service-mobile-en-offering-product-received',
        title: 'PRODUCT RECEIVED',
        content: {
          format: 'sanitized-html',
          html: '<ul><li>24/7 Technical Support</li><li>Full Source Code</li><li>Professional &amp; User-Friendly Product</li><li>App Store / Google Play Publishing</li><li>User &amp; Maintenance Documentation</li><li>UI/UX Design Files</li><li>App Management Account (if uploaded to App Store / Google Play)</li></ul>',
          assetIds: [],
          sources: [{ file: 'en/app-mobile-development/index.html', line: 1783 }],
        },
      },
    ],
    sectionCopy: {
      benefits: {
        eyebrow: 'Mobile App Design at Sova',
        title: 'Develop Your Business Advantage on Mobile Platforms',
      },
      offerings: { eyebrow: 'Why choose us?', title: 'Why Choose Sova ?' },
      projects: {
        eyebrow: 'Sova',
        title: 'Some Recent Works We’re Really Proud Of.',
        titleLines: ['Some Recent Works', 'We’re Really Proud Of.'],
      },
      testimonials: { eyebrow: 'Sova', title: 'Customer Reviews' },
      faq: { title: 'Frequently Asked Questions' },
    },
  },
];
