// Generated by scripts/import (npm run import) — do not edit.
import type { Service } from '@/types/content';

export const websiteServices: Service[] = [
  {
    id: 'service-website-vi',
    locale: 'vi',
    path: '/thiet-ke-website/',
    title: 'Thiết kế website',
    translationKey: 'service-website',
    sources: [{ file: 'thiet-ke-website/index.html', line: 663, sourceId: '7233' }],
    key: 'website',
    summary:
      'Mỗi dự án không chỉ là cơ hội để tạo ra giá trị cho doanh nghiệp, mà còn là dịp để chúng ta trở thành đối tác đồng hành, mang lại giá trị cộng hưởng cho khách hàng thông qua những sản phẩm trải nghiệm số tinh tế.',
    homeSummary:
      'Một quy trình chuẩn từ nghiên cứu thiết kế đến xây dựng lập trình website là một điều rất quan trọng để cho ra được sản phẩm hoàn thiện nhất cho khách hàng',
    subServices: [],
    arrowHref: '/thiet-ke-website/',
    hero: {
      headingLines: ['Thiết kế Website', 'Chuyên Nghiệp'],
      description: {
        format: 'sanitized-html',
        html: '<p>Mỗi dự án không chỉ là cơ hội để tạo ra giá trị cho doanh nghiệp, mà còn là dịp để chúng ta trở thành đối tác đồng hành, mang lại giá trị cộng hưởng cho khách hàng thông qua những sản phẩm trải nghiệm số tinh tế.</p>',
        assetIds: [],
        sources: [{ file: 'thiet-ke-website/index.html', line: 689 }],
      },
      imageId: 'asset-29a02b2e8f',
      videoId: 'asset-a4fba457f5',
      cta: { label: 'Kết nối ngay →', href: '/lien-he/' },
    },
    benefits: [
      {
        id: 'service-website-vi-benefit-mo-rong-tep-khach-hang',
        title: 'Mở rộng tệp khách hàng',
        body: {
          format: 'sanitized-html',
          html: '<p>Hiện nay, người dùng ngày càng có xu hướng mua sắm trực tuyến. Đối với chủ cửa hàng, việc sở hữu một website bán hàng sẽ giúp tiện lợi trong việc xử lý đơn hàng và giao hàng online.</p>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-website/index.html', line: 953 }],
        },
        iconId: 'asset-c1503a392d',
      },
      {
        id: 'service-website-vi-benefit-tang-hieu-qua-quang-cao',
        title: 'Tăng hiệu quả quảng cáo',
        body: {
          format: 'sanitized-html',
          html: '<p>Website là trung tâm của mọi hoạt động quảng cáo trực tuyến. Với một website chuyên nghiệp, việc tối ưu hóa SEO và tăng cường hiệu quả chuyển đổi từ quảng cáo sẽ trở nên tốt hơn.</p>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-website/index.html', line: 1022 }],
        },
        iconId: 'asset-835a6a3fba',
      },
      {
        id: 'service-website-vi-benefit-nang-tam-thuong-hieu',
        title: 'Nâng tầm thương hiệu',
        body: {
          format: 'sanitized-html',
          html: '<p>Chúng tôi xây dựng website chuyên nghiệp với giao diện thu hút và hỗ trợ mua sắm trực tuyến dễ dàng. Điều này giúp khách hàng cảm thấy yêu thích và tin tưởng hơn vào sản phẩm và thương hiệu của bạn.</p>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-website/index.html', line: 1094 }],
        },
        iconId: 'asset-7a2614dbc2',
      },
      {
        id: 'service-website-vi-benefit-cham-soc-khach-hang-24-7',
        title: 'Chăm sóc khách hàng 24/7',
        body: {
          format: 'sanitized-html',
          html: '<p>Khách hàng có thể xem và đặt hàng bất cứ lúc nào, và bạn có thể tư vấn cho họ 24/7 trực tiếp trên website. Điều này sẽ giúp tăng doanh thu một cách nhanh chóng và hiệu quả.</p>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-website/index.html', line: 1166 }],
        },
        iconId: 'asset-b1da7704b5',
      },
    ],
    faqs: [
      { faqId: 'faq-vi-1645186170', order: 1 },
      { faqId: 'faq-vi-456273721', order: 2 },
      { faqId: 'faq-vi-1924093008', order: 3 },
      { faqId: 'faq-vi-516906674', order: 4 },
      { faqId: 'faq-vi-929024664', order: 5 },
      { faqId: 'faq-vi-3663110478', order: 6 },
      { faqId: 'faq-vi-2861923398', order: 7 },
      { faqId: 'faq-vi-673622836', order: 8 },
    ],
    testimonialIds: [
      'testimonial-feedback-ten',
      'testimonial-feedback-dong-a',
      'testimonial-feedback-vinatex',
    ],
    featuredProjectIds: [
      'project-2348',
      'project-2182',
      'project-2176',
      'project-2170',
      'project-2161',
      'project-2120',
    ],
    pricingId: 'pricing-website',
    seo: {
      title: 'Thiết kế website - Công ty thiết kế website chuyên nghiệp | Sova',
      description: 'Trang chủ / Dịch vụ / Thiết kế website',
      canonicalPath: '/thiet-ke-website/',
      imageId: 'asset-b1da605d35',
    },
    offerings: [
      {
        id: 'service-website-vi-offering-loi-ich',
        title: 'LỢI ÍCH',
        content: {
          format: 'sanitized-html',
          html: '<ul><li>Tăng khả năng tiếp cận khách hàng</li><li>Tạo dựng uy tín và thương hiệu</li><li>Tiết kiệm chi phí quảng cáo</li><li>Cải thiện dịch vụ khách hàng</li><li>Tăng doanh thu và khả năng chuyển đổi</li><li>Phân tích và đo lường hiệu quả</li><li>Tự động hóa các quy trình kinh doanh</li></ul>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-website/index.html', line: 4624 }],
        },
      },
      {
        id: 'service-website-vi-offering-cam-ket',
        title: 'CAM KẾT',
        content: {
          format: 'sanitized-html',
          html: '<ul><li>Giao diện thân thiện và dễ sử dụng</li><li>Thiết kế chuyên nghiệp và độc đáo</li><li>Tối ưu hóa trên mọi thiết bị</li><li>Tối ưu hoá chuẩn SEO</li><li>Tốc độ tải trang nhanh</li><li>Bảo mật dữ liệu website</li><li>Hỗ trợ và bảo trì sau khi hoàn thành</li></ul>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-website/index.html', line: 4873 }],
        },
      },
      {
        id: 'service-website-vi-offering-san-pham-nhan-duoc',
        title: 'SẢN PHẨM NHẬN ĐƯỢC',
        content: {
          format: 'sanitized-html',
          html: '<ul><li>Website hoàn thiện chuyên nghiệp</li><li>Tích hợp với Mạng xã hội</li><li>Bộ mã nguồn (Source Code)</li><li>Hướng dẫn sử dụng và Quản lý website</li><li>Tài Khoản Web Hosting (Nếu có)</li><li>Tính năng và Chức năng thân thiện</li><li>Tài Khoản Web Hosting (Nếu có)</li></ul>',
          assetIds: [],
          sources: [{ file: 'thiet-ke-website/index.html', line: 5122 }],
        },
      },
    ],
    sectionCopy: {
      benefits: {
        eyebrow: 'Thiết kế Website tại Sova',
        title: 'Phát triển lợi thế doanh nghiệp của bạn trên nền tảng số',
        titleLines: ['Phát triển lợi thế doanh nghiệp', 'của bạn trên nền tảng số'],
      },
      pricing: { eyebrow: 'Bảng giá dịch vụ', title: 'Thiết kế website' },
      offerings: {
        eyebrow: 'Why choose us',
        title: 'Tại sao nên chọn Sova',
        titleLines: ['Tại sao nên chọn', 'Sova'],
      },
      projects: {
        eyebrow: 'Sova',
        title: 'Dự án chứa đựng Tâm huyết Sáng tạo',
        titleLines: ['Dự án chứa đựng', 'Tâm huyết Sáng tạo'],
      },
      testimonials: {
        eyebrow: 'Sova',
        title: 'Khách hàng nhận xét về chúng tôi',
        titleLines: ['Khách hàng nhận xét', 'về chúng tôi'],
      },
      faq: { title: 'Những câu hỏi thường gặp' },
      contact: {
        eyebrow: '100 MÃ ƯU ĐÃI THÁNG NÀY',
        title: 'Bạn muốn hỗ trợ nhanh nhất để có ngay Website',
        description: 'Liên hệ với Sova',
      },
    },
  },
  {
    id: 'service-website-en',
    locale: 'en',
    path: '/en/website-development/',
    title: 'Website Development',
    translationKey: 'service-website',
    sources: [{ file: 'en/website-development/index.html', line: 663, sourceId: '7372' }],
    key: 'website',
    summary:
      'Each project is not only an opportunity to create value for businesses, but also a chance for us to become trusted partners—delivering synergistic value to clients through refined and impactful digital experiences.',
    homeSummary:
      'We implement a full-stack development pipeline—starting from in-depth user research, wireframing, UI/UX design to frontend and backend development—ensuring scalable, high-performance websites optimized for SEO, security, and cross-browser compatibility.',
    subServices: [],
    arrowHref: '/en/website-development/',
    hero: {
      headingLines: ['Professional', 'Website Development'],
      description: {
        format: 'sanitized-html',
        html: '<p>Each project is not only an opportunity to create value for businesses, but also a chance for us to become trusted partners—delivering synergistic value to clients through refined and impactful digital experiences.</p>',
        assetIds: [],
        sources: [{ file: 'en/website-development/index.html', line: 689 }],
      },
      imageId: 'asset-29a02b2e8f',
      videoId: 'asset-a4fba457f5',
      cta: { label: 'Connect now →', href: '/lien-he/' },
    },
    benefits: [
      {
        id: 'service-website-en-benefit-expand-your-customer-base',
        title: 'Expand Your Customer Base',
        body: {
          format: 'sanitized-html',
          html: '<p>Nowadays consumers are increasingly shifting toward online shopping. For store owners, having an eCommerce website makes it easier to manage orders and deliver products efficiently.</p>',
          assetIds: [],
          sources: [{ file: 'en/website-development/index.html', line: 950 }],
        },
        iconId: 'asset-c1503a392d',
      },
      {
        id: 'service-website-en-benefit-boost-advertising-performance',
        title: 'Boost Advertising Performance',
        body: {
          format: 'sanitized-html',
          html: '<p>Your website is the central hub for all online marketing activities. A professional website allows for better SEO optimization and improves conversion rates from digital advertising campaigns.</p>',
          assetIds: [],
          sources: [{ file: 'en/website-development/index.html', line: 1018 }],
        },
        iconId: 'asset-835a6a3fba',
      },
      {
        id: 'service-website-en-benefit-elevate-your-brand',
        title: 'Elevate Your Brand',
        body: {
          format: 'sanitized-html',
          html: '<p>We create professional websites with visually appealing designs and seamless shopping experiences. This enhances customer trust and affinity for your brand and products.</p>',
          assetIds: [],
          sources: [{ file: 'en/website-development/index.html', line: 1090 }],
        },
        iconId: 'asset-7a2614dbc2',
      },
      {
        id: 'service-website-en-benefit-24-7-support',
        title: '24/7 Support',
        body: {
          format: 'sanitized-html',
          html: '<p>Customers can browse and place orders anytime, and you can provide real-time support directly through the website. This leads to faster revenue growth and improved customer satisfaction.</p>',
          assetIds: [],
          sources: [{ file: 'en/website-development/index.html', line: 1162 }],
        },
        iconId: 'asset-b1da7704b5',
      },
    ],
    faqs: [
      { faqId: 'faq-en-3827344023', order: 1 },
      { faqId: 'faq-en-2208551884', order: 2 },
      { faqId: 'faq-en-2191303423', order: 3 },
      { faqId: 'faq-en-337397211', order: 4 },
      { faqId: 'faq-en-2538705021', order: 5 },
      { faqId: 'faq-en-3829737620', order: 6 },
      { faqId: 'faq-en-3960288154', order: 7 },
      { faqId: 'faq-en-1937331324', order: 8 },
    ],
    testimonialIds: [
      'testimonial-feedback-ten',
      'testimonial-feedback-dong-a',
      'testimonial-feedback-vinatex',
    ],
    featuredProjectIds: [],
    pricingId: 'pricing-website',
    seo: {
      title: 'Website Development - Công ty thiết kế website chuyên nghiệp | Sova',
      description: 'Home / Services / Website Development',
      canonicalPath: '/en/website-development/',
      imageId: 'asset-b1da605d35',
    },
    offerings: [
      {
        id: 'service-website-en-offering-benefits',
        title: 'BENEFITS',
        content: {
          format: 'sanitized-html',
          html: '<ul><li>Expand Your Customer Reach</li><li>Establish Brand Authority &amp; Trust</li><li>Optimize Advertising Costs</li><li>Enhance Customer Experience</li><li>Drive Revenue &amp; Improve Conversion Rates</li><li>Measure &amp; Optimize Performance</li><li>Automate Business Workflows</li></ul>',
          assetIds: [],
          sources: [{ file: 'en/website-development/index.html', line: 4477 }],
        },
      },
      {
        id: 'service-website-en-offering-commitments',
        title: 'COMMITMENTS',
        content: {
          format: 'sanitized-html',
          html: '<ul><li>User-Friendly and Intuitive Interface</li><li>Professional and Unique Design</li><li>Optimized for All Devices</li><li>SEO-Optimized for Search Engine Visibility</li><li>Fast Page Load Speed</li><li>Robust Website Security</li><li>Post-Launch Support and Maintenance</li></ul>',
          assetIds: [],
          sources: [{ file: 'en/website-development/index.html', line: 4726 }],
        },
      },
      {
        id: 'service-website-en-offering-products-received',
        title: 'PRODUCTS RECEIVED',
        content: {
          format: 'sanitized-html',
          html: '<ul><li>Completed Professional Website</li><li>Social Media Integration</li><li>Source Code Package</li><li>User and Website Management Guide</li><li>Web Hosting Account (If applicable)</li><li>User-Friendly Features and Functions</li><li>Web Hosting Account (If applicable)</li></ul>',
          assetIds: [],
          sources: [{ file: 'en/website-development/index.html', line: 4975 }],
        },
      },
    ],
    sectionCopy: {
      benefits: {
        eyebrow: 'Website Development at Sova',
        title: 'Drive Your Business Growth with a Strategic Digital Presence',
      },
      pricing: { eyebrow: 'Service Pricing Table', title: 'Website Development' },
      offerings: { eyebrow: 'Why choose us', title: 'Why Choose Sova ?' },
      projects: {
        eyebrow: 'Sova',
        title: 'Some Recent Works We’re Really Proud Of.',
        titleLines: ['Some Recent Works', 'We’re Really Proud Of.'],
      },
      testimonials: { eyebrow: 'Sova', title: 'Customer Reviews' },
      faq: { title: 'Frequently Asked Questions' },
      contact: {
        title: 'You want support fastest to have an immediate Website',
        description: 'Contact Sova',
      },
    },
  },
];
